// Code generated by ent, DO NOT EDIT.

package privatechat

import (
	"AtoiTalkAPI/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldID, id))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldChatID, v))
}

// User1ID applies equality check predicate on the "user1_id" field. It's identical to User1IDEQ.
func User1ID(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1ID, v))
}

// User2ID applies equality check predicate on the "user2_id" field. It's identical to User2IDEQ.
func User2ID(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2ID, v))
}

// User1LastReadAt applies equality check predicate on the "user1_last_read_at" field. It's identical to User1LastReadAtEQ.
func User1LastReadAt(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1LastReadAt, v))
}

// User2LastReadAt applies equality check predicate on the "user2_last_read_at" field. It's identical to User2LastReadAtEQ.
func User2LastReadAt(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2LastReadAt, v))
}

// User1HiddenAt applies equality check predicate on the "user1_hidden_at" field. It's identical to User1HiddenAtEQ.
func User1HiddenAt(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1HiddenAt, v))
}

// User2HiddenAt applies equality check predicate on the "user2_hidden_at" field. It's identical to User2HiddenAtEQ.
func User2HiddenAt(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2HiddenAt, v))
}

// User1UnreadCount applies equality check predicate on the "user1_unread_count" field. It's identical to User1UnreadCountEQ.
func User1UnreadCount(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1UnreadCount, v))
}

// User2UnreadCount applies equality check predicate on the "user2_unread_count" field. It's identical to User2UnreadCountEQ.
func User2UnreadCount(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2UnreadCount, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldChatID, vs...))
}

// User1IDEQ applies the EQ predicate on the "user1_id" field.
func User1IDEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1ID, v))
}

// User1IDNEQ applies the NEQ predicate on the "user1_id" field.
func User1IDNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser1ID, v))
}

// User1IDIn applies the In predicate on the "user1_id" field.
func User1IDIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser1ID, vs...))
}

// User1IDNotIn applies the NotIn predicate on the "user1_id" field.
func User1IDNotIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser1ID, vs...))
}

// User2IDEQ applies the EQ predicate on the "user2_id" field.
func User2IDEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2ID, v))
}

// User2IDNEQ applies the NEQ predicate on the "user2_id" field.
func User2IDNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser2ID, v))
}

// User2IDIn applies the In predicate on the "user2_id" field.
func User2IDIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser2ID, vs...))
}

// User2IDNotIn applies the NotIn predicate on the "user2_id" field.
func User2IDNotIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser2ID, vs...))
}

// User1LastReadAtEQ applies the EQ predicate on the "user1_last_read_at" field.
func User1LastReadAtEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1LastReadAt, v))
}

// User1LastReadAtNEQ applies the NEQ predicate on the "user1_last_read_at" field.
func User1LastReadAtNEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser1LastReadAt, v))
}

// User1LastReadAtIn applies the In predicate on the "user1_last_read_at" field.
func User1LastReadAtIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser1LastReadAt, vs...))
}

// User1LastReadAtNotIn applies the NotIn predicate on the "user1_last_read_at" field.
func User1LastReadAtNotIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser1LastReadAt, vs...))
}

// User1LastReadAtGT applies the GT predicate on the "user1_last_read_at" field.
func User1LastReadAtGT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser1LastReadAt, v))
}

// User1LastReadAtGTE applies the GTE predicate on the "user1_last_read_at" field.
func User1LastReadAtGTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser1LastReadAt, v))
}

// User1LastReadAtLT applies the LT predicate on the "user1_last_read_at" field.
func User1LastReadAtLT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser1LastReadAt, v))
}

// User1LastReadAtLTE applies the LTE predicate on the "user1_last_read_at" field.
func User1LastReadAtLTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser1LastReadAt, v))
}

// User1LastReadAtIsNil applies the IsNil predicate on the "user1_last_read_at" field.
func User1LastReadAtIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIsNull(FieldUser1LastReadAt))
}

// User1LastReadAtNotNil applies the NotNil predicate on the "user1_last_read_at" field.
func User1LastReadAtNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotNull(FieldUser1LastReadAt))
}

// User2LastReadAtEQ applies the EQ predicate on the "user2_last_read_at" field.
func User2LastReadAtEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2LastReadAt, v))
}

// User2LastReadAtNEQ applies the NEQ predicate on the "user2_last_read_at" field.
func User2LastReadAtNEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser2LastReadAt, v))
}

// User2LastReadAtIn applies the In predicate on the "user2_last_read_at" field.
func User2LastReadAtIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser2LastReadAt, vs...))
}

// User2LastReadAtNotIn applies the NotIn predicate on the "user2_last_read_at" field.
func User2LastReadAtNotIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser2LastReadAt, vs...))
}

// User2LastReadAtGT applies the GT predicate on the "user2_last_read_at" field.
func User2LastReadAtGT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser2LastReadAt, v))
}

// User2LastReadAtGTE applies the GTE predicate on the "user2_last_read_at" field.
func User2LastReadAtGTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser2LastReadAt, v))
}

// User2LastReadAtLT applies the LT predicate on the "user2_last_read_at" field.
func User2LastReadAtLT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser2LastReadAt, v))
}

// User2LastReadAtLTE applies the LTE predicate on the "user2_last_read_at" field.
func User2LastReadAtLTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser2LastReadAt, v))
}

// User2LastReadAtIsNil applies the IsNil predicate on the "user2_last_read_at" field.
func User2LastReadAtIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIsNull(FieldUser2LastReadAt))
}

// User2LastReadAtNotNil applies the NotNil predicate on the "user2_last_read_at" field.
func User2LastReadAtNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotNull(FieldUser2LastReadAt))
}

// User1HiddenAtEQ applies the EQ predicate on the "user1_hidden_at" field.
func User1HiddenAtEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1HiddenAt, v))
}

// User1HiddenAtNEQ applies the NEQ predicate on the "user1_hidden_at" field.
func User1HiddenAtNEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser1HiddenAt, v))
}

// User1HiddenAtIn applies the In predicate on the "user1_hidden_at" field.
func User1HiddenAtIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser1HiddenAt, vs...))
}

// User1HiddenAtNotIn applies the NotIn predicate on the "user1_hidden_at" field.
func User1HiddenAtNotIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser1HiddenAt, vs...))
}

// User1HiddenAtGT applies the GT predicate on the "user1_hidden_at" field.
func User1HiddenAtGT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser1HiddenAt, v))
}

// User1HiddenAtGTE applies the GTE predicate on the "user1_hidden_at" field.
func User1HiddenAtGTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser1HiddenAt, v))
}

// User1HiddenAtLT applies the LT predicate on the "user1_hidden_at" field.
func User1HiddenAtLT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser1HiddenAt, v))
}

// User1HiddenAtLTE applies the LTE predicate on the "user1_hidden_at" field.
func User1HiddenAtLTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser1HiddenAt, v))
}

// User1HiddenAtIsNil applies the IsNil predicate on the "user1_hidden_at" field.
func User1HiddenAtIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIsNull(FieldUser1HiddenAt))
}

// User1HiddenAtNotNil applies the NotNil predicate on the "user1_hidden_at" field.
func User1HiddenAtNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotNull(FieldUser1HiddenAt))
}

// User2HiddenAtEQ applies the EQ predicate on the "user2_hidden_at" field.
func User2HiddenAtEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2HiddenAt, v))
}

// User2HiddenAtNEQ applies the NEQ predicate on the "user2_hidden_at" field.
func User2HiddenAtNEQ(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser2HiddenAt, v))
}

// User2HiddenAtIn applies the In predicate on the "user2_hidden_at" field.
func User2HiddenAtIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser2HiddenAt, vs...))
}

// User2HiddenAtNotIn applies the NotIn predicate on the "user2_hidden_at" field.
func User2HiddenAtNotIn(vs ...time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser2HiddenAt, vs...))
}

// User2HiddenAtGT applies the GT predicate on the "user2_hidden_at" field.
func User2HiddenAtGT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser2HiddenAt, v))
}

// User2HiddenAtGTE applies the GTE predicate on the "user2_hidden_at" field.
func User2HiddenAtGTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser2HiddenAt, v))
}

// User2HiddenAtLT applies the LT predicate on the "user2_hidden_at" field.
func User2HiddenAtLT(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser2HiddenAt, v))
}

// User2HiddenAtLTE applies the LTE predicate on the "user2_hidden_at" field.
func User2HiddenAtLTE(v time.Time) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser2HiddenAt, v))
}

// User2HiddenAtIsNil applies the IsNil predicate on the "user2_hidden_at" field.
func User2HiddenAtIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIsNull(FieldUser2HiddenAt))
}

// User2HiddenAtNotNil applies the NotNil predicate on the "user2_hidden_at" field.
func User2HiddenAtNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotNull(FieldUser2HiddenAt))
}

// User1UnreadCountEQ applies the EQ predicate on the "user1_unread_count" field.
func User1UnreadCountEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser1UnreadCount, v))
}

// User1UnreadCountNEQ applies the NEQ predicate on the "user1_unread_count" field.
func User1UnreadCountNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser1UnreadCount, v))
}

// User1UnreadCountIn applies the In predicate on the "user1_unread_count" field.
func User1UnreadCountIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser1UnreadCount, vs...))
}

// User1UnreadCountNotIn applies the NotIn predicate on the "user1_unread_count" field.
func User1UnreadCountNotIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser1UnreadCount, vs...))
}

// User1UnreadCountGT applies the GT predicate on the "user1_unread_count" field.
func User1UnreadCountGT(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser1UnreadCount, v))
}

// User1UnreadCountGTE applies the GTE predicate on the "user1_unread_count" field.
func User1UnreadCountGTE(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser1UnreadCount, v))
}

// User1UnreadCountLT applies the LT predicate on the "user1_unread_count" field.
func User1UnreadCountLT(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser1UnreadCount, v))
}

// User1UnreadCountLTE applies the LTE predicate on the "user1_unread_count" field.
func User1UnreadCountLTE(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser1UnreadCount, v))
}

// User2UnreadCountEQ applies the EQ predicate on the "user2_unread_count" field.
func User2UnreadCountEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldEQ(FieldUser2UnreadCount, v))
}

// User2UnreadCountNEQ applies the NEQ predicate on the "user2_unread_count" field.
func User2UnreadCountNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNEQ(FieldUser2UnreadCount, v))
}

// User2UnreadCountIn applies the In predicate on the "user2_unread_count" field.
func User2UnreadCountIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldIn(FieldUser2UnreadCount, vs...))
}

// User2UnreadCountNotIn applies the NotIn predicate on the "user2_unread_count" field.
func User2UnreadCountNotIn(vs ...int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldNotIn(FieldUser2UnreadCount, vs...))
}

// User2UnreadCountGT applies the GT predicate on the "user2_unread_count" field.
func User2UnreadCountGT(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGT(FieldUser2UnreadCount, v))
}

// User2UnreadCountGTE applies the GTE predicate on the "user2_unread_count" field.
func User2UnreadCountGTE(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldGTE(FieldUser2UnreadCount, v))
}

// User2UnreadCountLT applies the LT predicate on the "user2_unread_count" field.
func User2UnreadCountLT(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLT(FieldUser2UnreadCount, v))
}

// User2UnreadCountLTE applies the LTE predicate on the "user2_unread_count" field.
func User2UnreadCountLTE(v int) predicate.PrivateChat {
	return predicate.PrivateChat(sql.FieldLTE(FieldUser2UnreadCount, v))
}

// HasChat applies the HasEdge predicate on the "chat" edge.
func HasChat() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ChatTable, ChatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatWith applies the HasEdge predicate on the "chat" edge with a given conditions (other predicates).
func HasChatWith(preds ...predicate.Chat) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := newChatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser1 applies the HasEdge predicate on the "user1" edge.
func HasUser1() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User1Table, User1Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser1With applies the HasEdge predicate on the "user1" edge with a given conditions (other predicates).
func HasUser1With(preds ...predicate.User) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := newUser1Step()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser2 applies the HasEdge predicate on the "user2" edge.
func HasUser2() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User2Table, User2Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser2With applies the HasEdge predicate on the "user2" edge with a given conditions (other predicates).
func HasUser2With(preds ...predicate.User) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := newUser2Step()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(sql.NotPredicates(p))
}
