// Code generated by ent, DO NOT EDIT.

package chat

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the chat type in the database.
	Label = "chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldLastMessageID holds the string denoting the last_message_id field in the database.
	FieldLastMessageID = "last_message_id"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// EdgePrivateChat holds the string denoting the private_chat edge name in mutations.
	EdgePrivateChat = "private_chat"
	// EdgeGroupChat holds the string denoting the group_chat edge name in mutations.
	EdgeGroupChat = "group_chat"
	// EdgeLastMessage holds the string denoting the last_message edge name in mutations.
	EdgeLastMessage = "last_message"
	// Table holds the table name of the chat in the database.
	Table = "chats"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "chat_id"
	// PrivateChatTable is the table that holds the private_chat relation/edge.
	PrivateChatTable = "private_chats"
	// PrivateChatInverseTable is the table name for the PrivateChat entity.
	// It exists in this package in order to avoid circular dependency with the "privatechat" package.
	PrivateChatInverseTable = "private_chats"
	// PrivateChatColumn is the table column denoting the private_chat relation/edge.
	PrivateChatColumn = "chat_id"
	// GroupChatTable is the table that holds the group_chat relation/edge.
	GroupChatTable = "group_chats"
	// GroupChatInverseTable is the table name for the GroupChat entity.
	// It exists in this package in order to avoid circular dependency with the "groupchat" package.
	GroupChatInverseTable = "group_chats"
	// GroupChatColumn is the table column denoting the group_chat relation/edge.
	GroupChatColumn = "chat_id"
	// LastMessageTable is the table that holds the last_message relation/edge.
	LastMessageTable = "chats"
	// LastMessageInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	LastMessageInverseTable = "messages"
	// LastMessageColumn is the table column denoting the last_message relation/edge.
	LastMessageColumn = "last_message_id"
)

// Columns holds all SQL columns for chat fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldType,
	FieldLastMessageID,
	FieldLastMessageAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypePrivate Type = "private"
	TypeGroup   Type = "group"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypePrivate, TypeGroup:
		return nil
	default:
		return fmt.Errorf("chat: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Chat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByLastMessageID orders the results by the last_message_id field.
func ByLastMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageID, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrivateChatField orders the results by private_chat field.
func ByPrivateChatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrivateChatStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupChatField orders the results by group_chat field.
func ByGroupChatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupChatStep(), sql.OrderByField(field, opts...))
	}
}

// ByLastMessageField orders the results by last_message field.
func ByLastMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLastMessageStep(), sql.OrderByField(field, opts...))
	}
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
func newPrivateChatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrivateChatInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PrivateChatTable, PrivateChatColumn),
	)
}
func newGroupChatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupChatInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, GroupChatTable, GroupChatColumn),
	)
}
func newLastMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LastMessageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LastMessageTable, LastMessageColumn),
	)
}
