// Code generated by ent, DO NOT EDIT.

package groupchat

import (
	"AtoiTalkAPI/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLTE(FieldID, id))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldChatID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldCreatedBy, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldDescription, v))
}

// AvatarID applies equality check predicate on the "avatar_id" field. It's identical to AvatarIDEQ.
func AvatarID(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldAvatarID, v))
}

// IsPublic applies equality check predicate on the "is_public" field. It's identical to IsPublicEQ.
func IsPublic(v bool) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldIsPublic, v))
}

// InviteCode applies equality check predicate on the "invite_code" field. It's identical to InviteCodeEQ.
func InviteCode(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldInviteCode, v))
}

// InviteExpiresAt applies equality check predicate on the "invite_expires_at" field. It's identical to InviteExpiresAtEQ.
func InviteExpiresAt(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldInviteExpiresAt, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldChatID, vs...))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotNull(FieldCreatedBy))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContainsFold(FieldDescription, v))
}

// AvatarIDEQ applies the EQ predicate on the "avatar_id" field.
func AvatarIDEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldAvatarID, v))
}

// AvatarIDNEQ applies the NEQ predicate on the "avatar_id" field.
func AvatarIDNEQ(v uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldAvatarID, v))
}

// AvatarIDIn applies the In predicate on the "avatar_id" field.
func AvatarIDIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldAvatarID, vs...))
}

// AvatarIDNotIn applies the NotIn predicate on the "avatar_id" field.
func AvatarIDNotIn(vs ...uuid.UUID) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldAvatarID, vs...))
}

// AvatarIDIsNil applies the IsNil predicate on the "avatar_id" field.
func AvatarIDIsNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIsNull(FieldAvatarID))
}

// AvatarIDNotNil applies the NotNil predicate on the "avatar_id" field.
func AvatarIDNotNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotNull(FieldAvatarID))
}

// IsPublicEQ applies the EQ predicate on the "is_public" field.
func IsPublicEQ(v bool) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldIsPublic, v))
}

// IsPublicNEQ applies the NEQ predicate on the "is_public" field.
func IsPublicNEQ(v bool) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldIsPublic, v))
}

// InviteCodeEQ applies the EQ predicate on the "invite_code" field.
func InviteCodeEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldInviteCode, v))
}

// InviteCodeNEQ applies the NEQ predicate on the "invite_code" field.
func InviteCodeNEQ(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldInviteCode, v))
}

// InviteCodeIn applies the In predicate on the "invite_code" field.
func InviteCodeIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldInviteCode, vs...))
}

// InviteCodeNotIn applies the NotIn predicate on the "invite_code" field.
func InviteCodeNotIn(vs ...string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldInviteCode, vs...))
}

// InviteCodeGT applies the GT predicate on the "invite_code" field.
func InviteCodeGT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGT(FieldInviteCode, v))
}

// InviteCodeGTE applies the GTE predicate on the "invite_code" field.
func InviteCodeGTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGTE(FieldInviteCode, v))
}

// InviteCodeLT applies the LT predicate on the "invite_code" field.
func InviteCodeLT(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLT(FieldInviteCode, v))
}

// InviteCodeLTE applies the LTE predicate on the "invite_code" field.
func InviteCodeLTE(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLTE(FieldInviteCode, v))
}

// InviteCodeContains applies the Contains predicate on the "invite_code" field.
func InviteCodeContains(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContains(FieldInviteCode, v))
}

// InviteCodeHasPrefix applies the HasPrefix predicate on the "invite_code" field.
func InviteCodeHasPrefix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasPrefix(FieldInviteCode, v))
}

// InviteCodeHasSuffix applies the HasSuffix predicate on the "invite_code" field.
func InviteCodeHasSuffix(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldHasSuffix(FieldInviteCode, v))
}

// InviteCodeEqualFold applies the EqualFold predicate on the "invite_code" field.
func InviteCodeEqualFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEqualFold(FieldInviteCode, v))
}

// InviteCodeContainsFold applies the ContainsFold predicate on the "invite_code" field.
func InviteCodeContainsFold(v string) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldContainsFold(FieldInviteCode, v))
}

// InviteExpiresAtEQ applies the EQ predicate on the "invite_expires_at" field.
func InviteExpiresAtEQ(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldEQ(FieldInviteExpiresAt, v))
}

// InviteExpiresAtNEQ applies the NEQ predicate on the "invite_expires_at" field.
func InviteExpiresAtNEQ(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNEQ(FieldInviteExpiresAt, v))
}

// InviteExpiresAtIn applies the In predicate on the "invite_expires_at" field.
func InviteExpiresAtIn(vs ...time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIn(FieldInviteExpiresAt, vs...))
}

// InviteExpiresAtNotIn applies the NotIn predicate on the "invite_expires_at" field.
func InviteExpiresAtNotIn(vs ...time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotIn(FieldInviteExpiresAt, vs...))
}

// InviteExpiresAtGT applies the GT predicate on the "invite_expires_at" field.
func InviteExpiresAtGT(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGT(FieldInviteExpiresAt, v))
}

// InviteExpiresAtGTE applies the GTE predicate on the "invite_expires_at" field.
func InviteExpiresAtGTE(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldGTE(FieldInviteExpiresAt, v))
}

// InviteExpiresAtLT applies the LT predicate on the "invite_expires_at" field.
func InviteExpiresAtLT(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLT(FieldInviteExpiresAt, v))
}

// InviteExpiresAtLTE applies the LTE predicate on the "invite_expires_at" field.
func InviteExpiresAtLTE(v time.Time) predicate.GroupChat {
	return predicate.GroupChat(sql.FieldLTE(FieldInviteExpiresAt, v))
}

// InviteExpiresAtIsNil applies the IsNil predicate on the "invite_expires_at" field.
func InviteExpiresAtIsNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldIsNull(FieldInviteExpiresAt))
}

// InviteExpiresAtNotNil applies the NotNil predicate on the "invite_expires_at" field.
func InviteExpiresAtNotNil() predicate.GroupChat {
	return predicate.GroupChat(sql.FieldNotNull(FieldInviteExpiresAt))
}

// HasAvatar applies the HasEdge predicate on the "avatar" edge.
func HasAvatar() predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AvatarTable, AvatarColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAvatarWith applies the HasEdge predicate on the "avatar" edge with a given conditions (other predicates).
func HasAvatarWith(preds ...predicate.Media) predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := newAvatarStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChat applies the HasEdge predicate on the "chat" edge.
func HasChat() predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ChatTable, ChatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatWith applies the HasEdge predicate on the "chat" edge with a given conditions (other predicates).
func HasChatWith(preds ...predicate.Chat) predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := newChatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.GroupMember) predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReports applies the HasEdge predicate on the "reports" edge.
func HasReports() predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ReportsTable, ReportsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReportsWith applies the HasEdge predicate on the "reports" edge with a given conditions (other predicates).
func HasReportsWith(preds ...predicate.Report) predicate.GroupChat {
	return predicate.GroupChat(func(s *sql.Selector) {
		step := newReportsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupChat) predicate.GroupChat {
	return predicate.GroupChat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupChat) predicate.GroupChat {
	return predicate.GroupChat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupChat) predicate.GroupChat {
	return predicate.GroupChat(sql.NotPredicates(p))
}
