// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/chat"
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/message"
	"AtoiTalkAPI/ent/privatechat"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChatCreate is the builder for creating a Chat entity.
type ChatCreate struct {
	config
	mutation *ChatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatCreate) SetCreatedAt(v time.Time) *ChatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableCreatedAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatCreate) SetUpdatedAt(v time.Time) *ChatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableUpdatedAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ChatCreate) SetType(v chat.Type) *ChatCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetLastMessageID sets the "last_message_id" field.
func (_c *ChatCreate) SetLastMessageID(v uuid.UUID) *ChatCreate {
	_c.mutation.SetLastMessageID(v)
	return _c
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_c *ChatCreate) SetNillableLastMessageID(v *uuid.UUID) *ChatCreate {
	if v != nil {
		_c.SetLastMessageID(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ChatCreate) SetLastMessageAt(v time.Time) *ChatCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableLastMessageAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatCreate) SetID(v uuid.UUID) *ChatCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChatCreate) SetNillableID(v *uuid.UUID) *ChatCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ChatCreate) AddMessageIDs(ids ...uuid.UUID) *ChatCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ChatCreate) AddMessages(v ...*Message) *ChatCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// SetPrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID.
func (_c *ChatCreate) SetPrivateChatID(id uuid.UUID) *ChatCreate {
	_c.mutation.SetPrivateChatID(id)
	return _c
}

// SetNillablePrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID if the given value is not nil.
func (_c *ChatCreate) SetNillablePrivateChatID(id *uuid.UUID) *ChatCreate {
	if id != nil {
		_c = _c.SetPrivateChatID(*id)
	}
	return _c
}

// SetPrivateChat sets the "private_chat" edge to the PrivateChat entity.
func (_c *ChatCreate) SetPrivateChat(v *PrivateChat) *ChatCreate {
	return _c.SetPrivateChatID(v.ID)
}

// SetGroupChatID sets the "group_chat" edge to the GroupChat entity by ID.
func (_c *ChatCreate) SetGroupChatID(id uuid.UUID) *ChatCreate {
	_c.mutation.SetGroupChatID(id)
	return _c
}

// SetNillableGroupChatID sets the "group_chat" edge to the GroupChat entity by ID if the given value is not nil.
func (_c *ChatCreate) SetNillableGroupChatID(id *uuid.UUID) *ChatCreate {
	if id != nil {
		_c = _c.SetGroupChatID(*id)
	}
	return _c
}

// SetGroupChat sets the "group_chat" edge to the GroupChat entity.
func (_c *ChatCreate) SetGroupChat(v *GroupChat) *ChatCreate {
	return _c.SetGroupChatID(v.ID)
}

// SetLastMessage sets the "last_message" edge to the Message entity.
func (_c *ChatCreate) SetLastMessage(v *Message) *ChatCreate {
	return _c.SetLastMessageID(v.ID)
}

// Mutation returns the ChatMutation object of the builder.
func (_c *ChatCreate) Mutation() *ChatMutation {
	return _c.mutation
}

// Save creates the Chat in the database.
func (_c *ChatCreate) Save(ctx context.Context) (*Chat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatCreate) SaveX(ctx context.Context) *Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chat.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chat.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chat.updated_at"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Chat.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := chat.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Chat.type": %w`, err)}
		}
	}
	return nil
}

func (_c *ChatCreate) sqlSave(ctx context.Context) (*Chat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatCreate) createSpec() (*Chat, *sqlgraph.CreateSpec) {
	var (
		_node = &Chat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chat.Table, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(chat.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(chat.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PrivateChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.PrivateChatTable,
			Columns: []string{chat.PrivateChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(privatechat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.GroupChatTable,
			Columns: []string{chat.GroupChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LastMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chat.LastMessageTable,
			Columns: []string{chat.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LastMessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chat.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatCreate) OnConflict(opts ...sql.ConflictOption) *ChatUpsertOne {
	_c.conflict = opts
	return &ChatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatCreate) OnConflictColumns(columns ...string) *ChatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatUpsertOne{
		create: _c,
	}
}

type (
	// ChatUpsertOne is the builder for "upsert"-ing
	//  one Chat node.
	ChatUpsertOne struct {
		create *ChatCreate
	}

	// ChatUpsert is the "OnConflict" setter.
	ChatUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsert) SetUpdatedAt(v time.Time) *ChatUpsert {
	u.Set(chat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsert) UpdateUpdatedAt() *ChatUpsert {
	u.SetExcluded(chat.FieldUpdatedAt)
	return u
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ChatUpsert) SetLastMessageID(v uuid.UUID) *ChatUpsert {
	u.Set(chat.FieldLastMessageID, v)
	return u
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ChatUpsert) UpdateLastMessageID() *ChatUpsert {
	u.SetExcluded(chat.FieldLastMessageID)
	return u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ChatUpsert) ClearLastMessageID() *ChatUpsert {
	u.SetNull(chat.FieldLastMessageID)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatUpsert) SetLastMessageAt(v time.Time) *ChatUpsert {
	u.Set(chat.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatUpsert) UpdateLastMessageAt() *ChatUpsert {
	u.SetExcluded(chat.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatUpsert) ClearLastMessageAt() *ChatUpsert {
	u.SetNull(chat.FieldLastMessageAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChatUpsertOne) UpdateNewValues() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chat.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chat.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(chat.FieldType)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatUpsertOne) Ignore() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatUpsertOne) DoNothing() *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatCreate.OnConflict
// documentation for more info.
func (u *ChatUpsertOne) Update(set func(*ChatUpsert)) *ChatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsertOne) SetUpdatedAt(v time.Time) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateUpdatedAt() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ChatUpsertOne) SetLastMessageID(v uuid.UUID) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateLastMessageID() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ChatUpsertOne) ClearLastMessageID() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatUpsertOne) SetLastMessageAt(v time.Time) *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatUpsertOne) UpdateLastMessageAt() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatUpsertOne) ClearLastMessageAt() *ChatUpsertOne {
	return u.Update(func(s *ChatUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *ChatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ChatUpsertOne.ID is not supported by MySQL driver. Use ChatUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatCreateBulk is the builder for creating many Chat entities in bulk.
type ChatCreateBulk struct {
	config
	err      error
	builders []*ChatCreate
	conflict []sql.ConflictOption
}

// Save creates the Chat entities in the database.
func (_c *ChatCreateBulk) Save(ctx context.Context) ([]*Chat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatCreateBulk) SaveX(ctx context.Context) []*Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatUpsertBulk {
	_c.conflict = opts
	return &ChatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatCreateBulk) OnConflictColumns(columns ...string) *ChatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatUpsertBulk{
		create: _c,
	}
}

// ChatUpsertBulk is the builder for "upsert"-ing
// a bulk of Chat nodes.
type ChatUpsertBulk struct {
	create *ChatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChatUpsertBulk) UpdateNewValues() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chat.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chat.FieldCreatedAt)
			}
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(chat.FieldType)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatUpsertBulk) Ignore() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatUpsertBulk) DoNothing() *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatCreateBulk.OnConflict
// documentation for more info.
func (u *ChatUpsertBulk) Update(set func(*ChatUpsert)) *ChatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatUpsertBulk) SetUpdatedAt(v time.Time) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateUpdatedAt() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ChatUpsertBulk) SetLastMessageID(v uuid.UUID) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateLastMessageID() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ChatUpsertBulk) ClearLastMessageID() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ChatUpsertBulk) SetLastMessageAt(v time.Time) *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ChatUpsertBulk) UpdateLastMessageAt() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ChatUpsertBulk) ClearLastMessageAt() *ChatUpsertBulk {
	return u.Update(func(s *ChatUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *ChatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
