// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/chat"
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/message"
	"AtoiTalkAPI/ent/privatechat"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Chat is the model entity for the Chat schema.
type Chat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Type holds the value of the "type" field.
	Type chat.Type `json:"type,omitempty"`
	// LastMessageID holds the value of the "last_message_id" field.
	LastMessageID *int `json:"last_message_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatQuery when eager-loading is set.
	Edges        ChatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatEdges holds the relations/edges for other nodes in the graph.
type ChatEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// LastMessage holds the value of the last_message edge.
	LastMessage *Message `json:"last_message,omitempty"`
	// PrivateChat holds the value of the private_chat edge.
	PrivateChat *PrivateChat `json:"private_chat,omitempty"`
	// GroupChat holds the value of the group_chat edge.
	GroupChat *GroupChat `json:"group_chat,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ChatEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// LastMessageOrErr returns the LastMessage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatEdges) LastMessageOrErr() (*Message, error) {
	if e.LastMessage != nil {
		return e.LastMessage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "last_message"}
}

// PrivateChatOrErr returns the PrivateChat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatEdges) PrivateChatOrErr() (*PrivateChat, error) {
	if e.PrivateChat != nil {
		return e.PrivateChat, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: privatechat.Label}
	}
	return nil, &NotLoadedError{edge: "private_chat"}
}

// GroupChatOrErr returns the GroupChat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatEdges) GroupChatOrErr() (*GroupChat, error) {
	if e.GroupChat != nil {
		return e.GroupChat, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: groupchat.Label}
	}
	return nil, &NotLoadedError{edge: "group_chat"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chat.FieldID, chat.FieldLastMessageID:
			values[i] = new(sql.NullInt64)
		case chat.FieldType:
			values[i] = new(sql.NullString)
		case chat.FieldCreatedAt, chat.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chat fields.
func (_m *Chat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chat.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = chat.Type(value.String)
			}
		case chat.FieldLastMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_id", values[i])
			} else if value.Valid {
				_m.LastMessageID = new(int)
				*_m.LastMessageID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Chat.
// This includes values selected through modifiers, order, etc.
func (_m *Chat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the Chat entity.
func (_m *Chat) QueryMessages() *MessageQuery {
	return NewChatClient(_m.config).QueryMessages(_m)
}

// QueryLastMessage queries the "last_message" edge of the Chat entity.
func (_m *Chat) QueryLastMessage() *MessageQuery {
	return NewChatClient(_m.config).QueryLastMessage(_m)
}

// QueryPrivateChat queries the "private_chat" edge of the Chat entity.
func (_m *Chat) QueryPrivateChat() *PrivateChatQuery {
	return NewChatClient(_m.config).QueryPrivateChat(_m)
}

// QueryGroupChat queries the "group_chat" edge of the Chat entity.
func (_m *Chat) QueryGroupChat() *GroupChatQuery {
	return NewChatClient(_m.config).QueryGroupChat(_m)
}

// Update returns a builder for updating this Chat.
// Note that you need to call Chat.Unwrap() before calling this method if this Chat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Chat) Update() *ChatUpdateOne {
	return NewChatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Chat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Chat) Unwrap() *Chat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Chat) String() string {
	var builder strings.Builder
	builder.WriteString("Chat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	if v := _m.LastMessageID; v != nil {
		builder.WriteString("last_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Chats is a parsable slice of Chat.
type Chats []*Chat
