// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/groupmember"
	"AtoiTalkAPI/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// GroupMember is the model entity for the GroupMember schema.
type GroupMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GroupChatID holds the value of the "group_chat_id" field.
	GroupChatID uuid.UUID `json:"group_chat_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role groupmember.Role `json:"role,omitempty"`
	// LastReadAt holds the value of the "last_read_at" field.
	LastReadAt *time.Time `json:"last_read_at,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// UnreadCount holds the value of the "unread_count" field.
	UnreadCount int `json:"unread_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupMemberQuery when eager-loading is set.
	Edges        GroupMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupMemberEdges holds the relations/edges for other nodes in the graph.
type GroupMemberEdges struct {
	// GroupChat holds the value of the group_chat edge.
	GroupChat *GroupChat `json:"group_chat,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupChatOrErr returns the GroupChat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupMemberEdges) GroupChatOrErr() (*GroupChat, error) {
	if e.GroupChat != nil {
		return e.GroupChat, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: groupchat.Label}
	}
	return nil, &NotLoadedError{edge: "group_chat"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupmember.FieldUnreadCount:
			values[i] = new(sql.NullInt64)
		case groupmember.FieldRole:
			values[i] = new(sql.NullString)
		case groupmember.FieldLastReadAt, groupmember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case groupmember.FieldID, groupmember.FieldGroupChatID, groupmember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupMember fields.
func (_m *GroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case groupmember.FieldGroupChatID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_chat_id", values[i])
			} else if value != nil {
				_m.GroupChatID = *value
			}
		case groupmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case groupmember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = groupmember.Role(value.String)
			}
		case groupmember.FieldLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_at", values[i])
			} else if value.Valid {
				_m.LastReadAt = new(time.Time)
				*_m.LastReadAt = value.Time
			}
		case groupmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case groupmember.FieldUnreadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unread_count", values[i])
			} else if value.Valid {
				_m.UnreadCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupMember.
// This includes values selected through modifiers, order, etc.
func (_m *GroupMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroupChat queries the "group_chat" edge of the GroupMember entity.
func (_m *GroupMember) QueryGroupChat() *GroupChatQuery {
	return NewGroupMemberClient(_m.config).QueryGroupChat(_m)
}

// QueryUser queries the "user" edge of the GroupMember entity.
func (_m *GroupMember) QueryUser() *UserQuery {
	return NewGroupMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this GroupMember.
// Note that you need to call GroupMember.Unwrap() before calling this method if this GroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupMember) Update() *GroupMemberUpdateOne {
	return NewGroupMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupMember) Unwrap() *GroupMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("GroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupChatID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	if v := _m.LastReadAt; v != nil {
		builder.WriteString("last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("unread_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnreadCount))
	builder.WriteByte(')')
	return builder.String()
}

// GroupMembers is a parsable slice of GroupMember.
type GroupMembers []*GroupMember
