// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/media"
	"AtoiTalkAPI/ent/message"
	"AtoiTalkAPI/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Media is the model entity for the Media schema.
type Media struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// OriginalName holds the value of the "original_name" field.
	OriginalName string `json:"original_name,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// Category holds the value of the "category" field.
	Category media.Category `json:"category,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID *uuid.UUID `json:"message_id,omitempty"`
	// UploadedByID holds the value of the "uploaded_by_id" field.
	UploadedByID *uuid.UUID `json:"uploaded_by_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaQuery when eager-loading is set.
	Edges        MediaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaEdges holds the relations/edges for other nodes in the graph.
type MediaEdges struct {
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// UserAvatar holds the value of the user_avatar edge.
	UserAvatar *User `json:"user_avatar,omitempty"`
	// GroupAvatar holds the value of the group_avatar edge.
	GroupAvatar *GroupChat `json:"group_avatar,omitempty"`
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// Reports holds the value of the reports edge.
	Reports []*Report `json:"reports,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// UserAvatarOrErr returns the UserAvatar value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaEdges) UserAvatarOrErr() (*User, error) {
	if e.UserAvatar != nil {
		return e.UserAvatar, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user_avatar"}
}

// GroupAvatarOrErr returns the GroupAvatar value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaEdges) GroupAvatarOrErr() (*GroupChat, error) {
	if e.GroupAvatar != nil {
		return e.GroupAvatar, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: groupchat.Label}
	}
	return nil, &NotLoadedError{edge: "group_avatar"}
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// ReportsOrErr returns the Reports value or an error if the edge
// was not loaded in eager-loading.
func (e MediaEdges) ReportsOrErr() ([]*Report, error) {
	if e.loadedTypes[4] {
		return e.Reports, nil
	}
	return nil, &NotLoadedError{edge: "reports"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Media) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case media.FieldMessageID, media.FieldUploadedByID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case media.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case media.FieldFileName, media.FieldOriginalName, media.FieldMimeType, media.FieldCategory:
			values[i] = new(sql.NullString)
		case media.FieldCreatedAt, media.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case media.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Media fields.
func (_m *Media) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case media.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case media.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case media.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case media.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case media.FieldOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_name", values[i])
			} else if value.Valid {
				_m.OriginalName = value.String
			}
		case media.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case media.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case media.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = media.Category(value.String)
			}
		case media.FieldMessageID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = new(uuid.UUID)
				*_m.MessageID = *value.S.(*uuid.UUID)
			}
		case media.FieldUploadedByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by_id", values[i])
			} else if value.Valid {
				_m.UploadedByID = new(uuid.UUID)
				*_m.UploadedByID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Media.
// This includes values selected through modifiers, order, etc.
func (_m *Media) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the Media entity.
func (_m *Media) QueryMessage() *MessageQuery {
	return NewMediaClient(_m.config).QueryMessage(_m)
}

// QueryUserAvatar queries the "user_avatar" edge of the Media entity.
func (_m *Media) QueryUserAvatar() *UserQuery {
	return NewMediaClient(_m.config).QueryUserAvatar(_m)
}

// QueryGroupAvatar queries the "group_avatar" edge of the Media entity.
func (_m *Media) QueryGroupAvatar() *GroupChatQuery {
	return NewMediaClient(_m.config).QueryGroupAvatar(_m)
}

// QueryUploader queries the "uploader" edge of the Media entity.
func (_m *Media) QueryUploader() *UserQuery {
	return NewMediaClient(_m.config).QueryUploader(_m)
}

// QueryReports queries the "reports" edge of the Media entity.
func (_m *Media) QueryReports() *ReportQuery {
	return NewMediaClient(_m.config).QueryReports(_m)
}

// Update returns a builder for updating this Media.
// Note that you need to call Media.Unwrap() before calling this method if this Media
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Media) Update() *MediaUpdateOne {
	return NewMediaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Media entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Media) Unwrap() *Media {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Media is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Media) String() string {
	var builder strings.Builder
	builder.WriteString("Media(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("original_name=")
	builder.WriteString(_m.OriginalName)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	if v := _m.MessageID; v != nil {
		builder.WriteString("message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UploadedByID; v != nil {
		builder.WriteString("uploaded_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaSlice is a parsable slice of Media.
type MediaSlice []*Media
