// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/media"
	"AtoiTalkAPI/ent/message"
	"AtoiTalkAPI/ent/predicate"
	"AtoiTalkAPI/ent/report"
	"AtoiTalkAPI/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks     []Hook
	mutation  *MediaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdate) SetUpdatedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *MediaUpdate) SetFileName(v string) *MediaUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableFileName(v *string) *MediaUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaUpdate) SetOriginalName(v string) *MediaUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableOriginalName(v *string) *MediaUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *MediaUpdate) SetFileSize(v int64) *MediaUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableFileSize(v *int64) *MediaUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *MediaUpdate) AddFileSize(v int64) *MediaUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaUpdate) SetMimeType(v string) *MediaUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableMimeType(v *string) *MediaUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaUpdate) SetStatus(v media.Status) *MediaUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableStatus(v *media.Status) *MediaUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MediaUpdate) SetMessageID(v uuid.UUID) *MediaUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableMessageID(v *uuid.UUID) *MediaUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *MediaUpdate) ClearMessageID() *MediaUpdate {
	_u.mutation.ClearMessageID()
	return _u
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (_u *MediaUpdate) SetUploadedByID(v uuid.UUID) *MediaUpdate {
	_u.mutation.SetUploadedByID(v)
	return _u
}

// SetNillableUploadedByID sets the "uploaded_by_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableUploadedByID(v *uuid.UUID) *MediaUpdate {
	if v != nil {
		_u.SetUploadedByID(*v)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *MediaUpdate) SetMessage(v *Message) *MediaUpdate {
	return _u.SetMessageID(v.ID)
}

// SetUserAvatarID sets the "user_avatar" edge to the User entity by ID.
func (_u *MediaUpdate) SetUserAvatarID(id uuid.UUID) *MediaUpdate {
	_u.mutation.SetUserAvatarID(id)
	return _u
}

// SetNillableUserAvatarID sets the "user_avatar" edge to the User entity by ID if the given value is not nil.
func (_u *MediaUpdate) SetNillableUserAvatarID(id *uuid.UUID) *MediaUpdate {
	if id != nil {
		_u = _u.SetUserAvatarID(*id)
	}
	return _u
}

// SetUserAvatar sets the "user_avatar" edge to the User entity.
func (_u *MediaUpdate) SetUserAvatar(v *User) *MediaUpdate {
	return _u.SetUserAvatarID(v.ID)
}

// SetGroupAvatarID sets the "group_avatar" edge to the GroupChat entity by ID.
func (_u *MediaUpdate) SetGroupAvatarID(id uuid.UUID) *MediaUpdate {
	_u.mutation.SetGroupAvatarID(id)
	return _u
}

// SetNillableGroupAvatarID sets the "group_avatar" edge to the GroupChat entity by ID if the given value is not nil.
func (_u *MediaUpdate) SetNillableGroupAvatarID(id *uuid.UUID) *MediaUpdate {
	if id != nil {
		_u = _u.SetGroupAvatarID(*id)
	}
	return _u
}

// SetGroupAvatar sets the "group_avatar" edge to the GroupChat entity.
func (_u *MediaUpdate) SetGroupAvatar(v *GroupChat) *MediaUpdate {
	return _u.SetGroupAvatarID(v.ID)
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *MediaUpdate) SetUploaderID(id uuid.UUID) *MediaUpdate {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *MediaUpdate) SetUploader(v *User) *MediaUpdate {
	return _u.SetUploaderID(v.ID)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (_u *MediaUpdate) AddReportIDs(ids ...uuid.UUID) *MediaUpdate {
	_u.mutation.AddReportIDs(ids...)
	return _u
}

// AddReports adds the "reports" edges to the Report entity.
func (_u *MediaUpdate) AddReports(v ...*Report) *MediaUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReportIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdate) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *MediaUpdate) ClearMessage() *MediaUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUserAvatar clears the "user_avatar" edge to the User entity.
func (_u *MediaUpdate) ClearUserAvatar() *MediaUpdate {
	_u.mutation.ClearUserAvatar()
	return _u
}

// ClearGroupAvatar clears the "group_avatar" edge to the GroupChat entity.
func (_u *MediaUpdate) ClearGroupAvatar() *MediaUpdate {
	_u.mutation.ClearGroupAvatar()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *MediaUpdate) ClearUploader() *MediaUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// ClearReports clears all "reports" edges to the Report entity.
func (_u *MediaUpdate) ClearReports() *MediaUpdate {
	_u.mutation.ClearReports()
	return _u
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (_u *MediaUpdate) RemoveReportIDs(ids ...uuid.UUID) *MediaUpdate {
	_u.mutation.RemoveReportIDs(ids...)
	return _u
}

// RemoveReports removes "reports" edges to Report entities.
func (_u *MediaUpdate) RemoveReports(v ...*Report) *MediaUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdate) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := media.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Media.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := media.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "Media.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := media.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Media.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := media.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Media.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := media.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Media.status": %w`, err)}
		}
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Media.uploader"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MediaUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MediaUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MediaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(media.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(media.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(media.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(media.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(media.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(media.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.MessageTable,
			Columns: []string{media.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.MessageTable,
			Columns: []string{media.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAvatarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.UserAvatarTable,
			Columns: []string{media.UserAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAvatarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.UserAvatarTable,
			Columns: []string{media.UserAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupAvatarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.GroupAvatarTable,
			Columns: []string{media.GroupAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupAvatarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.GroupAvatarTable,
			Columns: []string{media.GroupAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.UploaderTable,
			Columns: []string{media.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.UploaderTable,
			Columns: []string{media.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReportsIDs(); len(nodes) > 0 && !_u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MediaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdateOne) SetUpdatedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *MediaUpdateOne) SetFileName(v string) *MediaUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableFileName(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaUpdateOne) SetOriginalName(v string) *MediaUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableOriginalName(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *MediaUpdateOne) SetFileSize(v int64) *MediaUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableFileSize(v *int64) *MediaUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *MediaUpdateOne) AddFileSize(v int64) *MediaUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaUpdateOne) SetMimeType(v string) *MediaUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableMimeType(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaUpdateOne) SetStatus(v media.Status) *MediaUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableStatus(v *media.Status) *MediaUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MediaUpdateOne) SetMessageID(v uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableMessageID(v *uuid.UUID) *MediaUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *MediaUpdateOne) ClearMessageID() *MediaUpdateOne {
	_u.mutation.ClearMessageID()
	return _u
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (_u *MediaUpdateOne) SetUploadedByID(v uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetUploadedByID(v)
	return _u
}

// SetNillableUploadedByID sets the "uploaded_by_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableUploadedByID(v *uuid.UUID) *MediaUpdateOne {
	if v != nil {
		_u.SetUploadedByID(*v)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *MediaUpdateOne) SetMessage(v *Message) *MediaUpdateOne {
	return _u.SetMessageID(v.ID)
}

// SetUserAvatarID sets the "user_avatar" edge to the User entity by ID.
func (_u *MediaUpdateOne) SetUserAvatarID(id uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetUserAvatarID(id)
	return _u
}

// SetNillableUserAvatarID sets the "user_avatar" edge to the User entity by ID if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableUserAvatarID(id *uuid.UUID) *MediaUpdateOne {
	if id != nil {
		_u = _u.SetUserAvatarID(*id)
	}
	return _u
}

// SetUserAvatar sets the "user_avatar" edge to the User entity.
func (_u *MediaUpdateOne) SetUserAvatar(v *User) *MediaUpdateOne {
	return _u.SetUserAvatarID(v.ID)
}

// SetGroupAvatarID sets the "group_avatar" edge to the GroupChat entity by ID.
func (_u *MediaUpdateOne) SetGroupAvatarID(id uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetGroupAvatarID(id)
	return _u
}

// SetNillableGroupAvatarID sets the "group_avatar" edge to the GroupChat entity by ID if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableGroupAvatarID(id *uuid.UUID) *MediaUpdateOne {
	if id != nil {
		_u = _u.SetGroupAvatarID(*id)
	}
	return _u
}

// SetGroupAvatar sets the "group_avatar" edge to the GroupChat entity.
func (_u *MediaUpdateOne) SetGroupAvatar(v *GroupChat) *MediaUpdateOne {
	return _u.SetGroupAvatarID(v.ID)
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *MediaUpdateOne) SetUploaderID(id uuid.UUID) *MediaUpdateOne {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *MediaUpdateOne) SetUploader(v *User) *MediaUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// AddReportIDs adds the "reports" edge to the Report entity by IDs.
func (_u *MediaUpdateOne) AddReportIDs(ids ...uuid.UUID) *MediaUpdateOne {
	_u.mutation.AddReportIDs(ids...)
	return _u
}

// AddReports adds the "reports" edges to the Report entity.
func (_u *MediaUpdateOne) AddReports(v ...*Report) *MediaUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReportIDs(ids...)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdateOne) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *MediaUpdateOne) ClearMessage() *MediaUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUserAvatar clears the "user_avatar" edge to the User entity.
func (_u *MediaUpdateOne) ClearUserAvatar() *MediaUpdateOne {
	_u.mutation.ClearUserAvatar()
	return _u
}

// ClearGroupAvatar clears the "group_avatar" edge to the GroupChat entity.
func (_u *MediaUpdateOne) ClearGroupAvatar() *MediaUpdateOne {
	_u.mutation.ClearGroupAvatar()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *MediaUpdateOne) ClearUploader() *MediaUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// ClearReports clears all "reports" edges to the Report entity.
func (_u *MediaUpdateOne) ClearReports() *MediaUpdateOne {
	_u.mutation.ClearReports()
	return _u
}

// RemoveReportIDs removes the "reports" edge to Report entities by IDs.
func (_u *MediaUpdateOne) RemoveReportIDs(ids ...uuid.UUID) *MediaUpdateOne {
	_u.mutation.RemoveReportIDs(ids...)
	return _u
}

// RemoveReports removes "reports" edges to Report entities.
func (_u *MediaUpdateOne) RemoveReports(v ...*Report) *MediaUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReportIDs(ids...)
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Media entity.
func (_u *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdateOne) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := media.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Media.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := media.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "Media.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := media.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "Media.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := media.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Media.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := media.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Media.status": %w`, err)}
		}
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Media.uploader"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MediaUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MediaUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(media.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(media.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(media.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(media.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(media.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(media.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.MessageTable,
			Columns: []string{media.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.MessageTable,
			Columns: []string{media.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAvatarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.UserAvatarTable,
			Columns: []string{media.UserAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAvatarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.UserAvatarTable,
			Columns: []string{media.UserAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupAvatarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.GroupAvatarTable,
			Columns: []string{media.GroupAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupAvatarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   media.GroupAvatarTable,
			Columns: []string{media.GroupAvatarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.UploaderTable,
			Columns: []string{media.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.UploaderTable,
			Columns: []string{media.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReportsIDs(); len(nodes) > 0 && !_u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   media.ReportsTable,
			Columns: media.ReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Media{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
