// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/chat"
	"AtoiTalkAPI/ent/predicate"
	"AtoiTalkAPI/ent/privatechat"
	"AtoiTalkAPI/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrivateChatQuery is the builder for querying PrivateChat entities.
type PrivateChatQuery struct {
	config
	ctx        *QueryContext
	order      []privatechat.OrderOption
	inters     []Interceptor
	predicates []predicate.PrivateChat
	withChat   *ChatQuery
	withUser1  *UserQuery
	withUser2  *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrivateChatQuery builder.
func (_q *PrivateChatQuery) Where(ps ...predicate.PrivateChat) *PrivateChatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PrivateChatQuery) Limit(limit int) *PrivateChatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PrivateChatQuery) Offset(offset int) *PrivateChatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PrivateChatQuery) Unique(unique bool) *PrivateChatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PrivateChatQuery) Order(o ...privatechat.OrderOption) *PrivateChatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChat chains the current query on the "chat" edge.
func (_q *PrivateChatQuery) QueryChat() *ChatQuery {
	query := (&ChatClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(privatechat.Table, privatechat.FieldID, selector),
			sqlgraph.To(chat.Table, chat.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, privatechat.ChatTable, privatechat.ChatColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser1 chains the current query on the "user1" edge.
func (_q *PrivateChatQuery) QueryUser1() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(privatechat.Table, privatechat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, privatechat.User1Table, privatechat.User1Column),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser2 chains the current query on the "user2" edge.
func (_q *PrivateChatQuery) QueryUser2() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(privatechat.Table, privatechat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, privatechat.User2Table, privatechat.User2Column),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PrivateChat entity from the query.
// Returns a *NotFoundError when no PrivateChat was found.
func (_q *PrivateChatQuery) First(ctx context.Context) (*PrivateChat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{privatechat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PrivateChatQuery) FirstX(ctx context.Context) *PrivateChat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PrivateChat ID from the query.
// Returns a *NotFoundError when no PrivateChat ID was found.
func (_q *PrivateChatQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{privatechat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PrivateChatQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PrivateChat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PrivateChat entity is found.
// Returns a *NotFoundError when no PrivateChat entities are found.
func (_q *PrivateChatQuery) Only(ctx context.Context) (*PrivateChat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{privatechat.Label}
	default:
		return nil, &NotSingularError{privatechat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PrivateChatQuery) OnlyX(ctx context.Context) *PrivateChat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PrivateChat ID in the query.
// Returns a *NotSingularError when more than one PrivateChat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PrivateChatQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{privatechat.Label}
	default:
		err = &NotSingularError{privatechat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PrivateChatQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PrivateChats.
func (_q *PrivateChatQuery) All(ctx context.Context) ([]*PrivateChat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PrivateChat, *PrivateChatQuery]()
	return withInterceptors[[]*PrivateChat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PrivateChatQuery) AllX(ctx context.Context) []*PrivateChat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PrivateChat IDs.
func (_q *PrivateChatQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(privatechat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PrivateChatQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PrivateChatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PrivateChatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PrivateChatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PrivateChatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PrivateChatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrivateChatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PrivateChatQuery) Clone() *PrivateChatQuery {
	if _q == nil {
		return nil
	}
	return &PrivateChatQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]privatechat.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PrivateChat{}, _q.predicates...),
		withChat:   _q.withChat.Clone(),
		withUser1:  _q.withUser1.Clone(),
		withUser2:  _q.withUser2.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithChat tells the query-builder to eager-load the nodes that are connected to
// the "chat" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrivateChatQuery) WithChat(opts ...func(*ChatQuery)) *PrivateChatQuery {
	query := (&ChatClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChat = query
	return _q
}

// WithUser1 tells the query-builder to eager-load the nodes that are connected to
// the "user1" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrivateChatQuery) WithUser1(opts ...func(*UserQuery)) *PrivateChatQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser1 = query
	return _q
}

// WithUser2 tells the query-builder to eager-load the nodes that are connected to
// the "user2" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrivateChatQuery) WithUser2(opts ...func(*UserQuery)) *PrivateChatQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser2 = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChatID uuid.UUID `json:"chat_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PrivateChat.Query().
//		GroupBy(privatechat.FieldChatID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PrivateChatQuery) GroupBy(field string, fields ...string) *PrivateChatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrivateChatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = privatechat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChatID uuid.UUID `json:"chat_id,omitempty"`
//	}
//
//	client.PrivateChat.Query().
//		Select(privatechat.FieldChatID).
//		Scan(ctx, &v)
func (_q *PrivateChatQuery) Select(fields ...string) *PrivateChatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PrivateChatSelect{PrivateChatQuery: _q}
	sbuild.label = privatechat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrivateChatSelect configured with the given aggregations.
func (_q *PrivateChatQuery) Aggregate(fns ...AggregateFunc) *PrivateChatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PrivateChatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !privatechat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PrivateChatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PrivateChat, error) {
	var (
		nodes       = []*PrivateChat{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withChat != nil,
			_q.withUser1 != nil,
			_q.withUser2 != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PrivateChat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PrivateChat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChat; query != nil {
		if err := _q.loadChat(ctx, query, nodes, nil,
			func(n *PrivateChat, e *Chat) { n.Edges.Chat = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser1; query != nil {
		if err := _q.loadUser1(ctx, query, nodes, nil,
			func(n *PrivateChat, e *User) { n.Edges.User1 = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser2; query != nil {
		if err := _q.loadUser2(ctx, query, nodes, nil,
			func(n *PrivateChat, e *User) { n.Edges.User2 = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PrivateChatQuery) loadChat(ctx context.Context, query *ChatQuery, nodes []*PrivateChat, init func(*PrivateChat), assign func(*PrivateChat, *Chat)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PrivateChat)
	for i := range nodes {
		fk := nodes[i].ChatID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chat.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chat_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PrivateChatQuery) loadUser1(ctx context.Context, query *UserQuery, nodes []*PrivateChat, init func(*PrivateChat), assign func(*PrivateChat, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PrivateChat)
	for i := range nodes {
		fk := nodes[i].User1ID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user1_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PrivateChatQuery) loadUser2(ctx context.Context, query *UserQuery, nodes []*PrivateChat, init func(*PrivateChat), assign func(*PrivateChat, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PrivateChat)
	for i := range nodes {
		fk := nodes[i].User2ID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user2_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PrivateChatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PrivateChatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(privatechat.Table, privatechat.Columns, sqlgraph.NewFieldSpec(privatechat.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, privatechat.FieldID)
		for i := range fields {
			if fields[i] != privatechat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChat != nil {
			_spec.Node.AddColumnOnce(privatechat.FieldChatID)
		}
		if _q.withUser1 != nil {
			_spec.Node.AddColumnOnce(privatechat.FieldUser1ID)
		}
		if _q.withUser2 != nil {
			_spec.Node.AddColumnOnce(privatechat.FieldUser2ID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PrivateChatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(privatechat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = privatechat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *PrivateChatQuery) ForUpdate(opts ...sql.LockOption) *PrivateChatQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *PrivateChatQuery) ForShare(opts ...sql.LockOption) *PrivateChatQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *PrivateChatQuery) Modify(modifiers ...func(s *sql.Selector)) *PrivateChatSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// PrivateChatGroupBy is the group-by builder for PrivateChat entities.
type PrivateChatGroupBy struct {
	selector
	build *PrivateChatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PrivateChatGroupBy) Aggregate(fns ...AggregateFunc) *PrivateChatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PrivateChatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrivateChatQuery, *PrivateChatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PrivateChatGroupBy) sqlScan(ctx context.Context, root *PrivateChatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrivateChatSelect is the builder for selecting fields of PrivateChat entities.
type PrivateChatSelect struct {
	*PrivateChatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PrivateChatSelect) Aggregate(fns ...AggregateFunc) *PrivateChatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PrivateChatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrivateChatQuery, *PrivateChatSelect](ctx, _s.PrivateChatQuery, _s, _s.inters, v)
}

func (_s *PrivateChatSelect) sqlScan(ctx context.Context, root *PrivateChatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *PrivateChatSelect) Modify(modifiers ...func(s *sql.Selector)) *PrivateChatSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
