// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/chat"
	"AtoiTalkAPI/ent/predicate"
	"AtoiTalkAPI/ent/privatechat"
	"AtoiTalkAPI/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PrivateChatUpdate is the builder for updating PrivateChat entities.
type PrivateChatUpdate struct {
	config
	hooks     []Hook
	mutation  *PrivateChatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PrivateChatUpdate builder.
func (_u *PrivateChatUpdate) Where(ps ...predicate.PrivateChat) *PrivateChatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *PrivateChatUpdate) SetChatID(v uuid.UUID) *PrivateChatUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableChatID(v *uuid.UUID) *PrivateChatUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetUser1ID sets the "user1_id" field.
func (_u *PrivateChatUpdate) SetUser1ID(v uuid.UUID) *PrivateChatUpdate {
	_u.mutation.SetUser1ID(v)
	return _u
}

// SetNillableUser1ID sets the "user1_id" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser1ID(v *uuid.UUID) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser1ID(*v)
	}
	return _u
}

// SetUser2ID sets the "user2_id" field.
func (_u *PrivateChatUpdate) SetUser2ID(v uuid.UUID) *PrivateChatUpdate {
	_u.mutation.SetUser2ID(v)
	return _u
}

// SetNillableUser2ID sets the "user2_id" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser2ID(v *uuid.UUID) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser2ID(*v)
	}
	return _u
}

// SetUser1LastReadAt sets the "user1_last_read_at" field.
func (_u *PrivateChatUpdate) SetUser1LastReadAt(v time.Time) *PrivateChatUpdate {
	_u.mutation.SetUser1LastReadAt(v)
	return _u
}

// SetNillableUser1LastReadAt sets the "user1_last_read_at" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser1LastReadAt(v *time.Time) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser1LastReadAt(*v)
	}
	return _u
}

// ClearUser1LastReadAt clears the value of the "user1_last_read_at" field.
func (_u *PrivateChatUpdate) ClearUser1LastReadAt() *PrivateChatUpdate {
	_u.mutation.ClearUser1LastReadAt()
	return _u
}

// SetUser2LastReadAt sets the "user2_last_read_at" field.
func (_u *PrivateChatUpdate) SetUser2LastReadAt(v time.Time) *PrivateChatUpdate {
	_u.mutation.SetUser2LastReadAt(v)
	return _u
}

// SetNillableUser2LastReadAt sets the "user2_last_read_at" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser2LastReadAt(v *time.Time) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser2LastReadAt(*v)
	}
	return _u
}

// ClearUser2LastReadAt clears the value of the "user2_last_read_at" field.
func (_u *PrivateChatUpdate) ClearUser2LastReadAt() *PrivateChatUpdate {
	_u.mutation.ClearUser2LastReadAt()
	return _u
}

// SetUser1HiddenAt sets the "user1_hidden_at" field.
func (_u *PrivateChatUpdate) SetUser1HiddenAt(v time.Time) *PrivateChatUpdate {
	_u.mutation.SetUser1HiddenAt(v)
	return _u
}

// SetNillableUser1HiddenAt sets the "user1_hidden_at" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser1HiddenAt(v *time.Time) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser1HiddenAt(*v)
	}
	return _u
}

// ClearUser1HiddenAt clears the value of the "user1_hidden_at" field.
func (_u *PrivateChatUpdate) ClearUser1HiddenAt() *PrivateChatUpdate {
	_u.mutation.ClearUser1HiddenAt()
	return _u
}

// SetUser2HiddenAt sets the "user2_hidden_at" field.
func (_u *PrivateChatUpdate) SetUser2HiddenAt(v time.Time) *PrivateChatUpdate {
	_u.mutation.SetUser2HiddenAt(v)
	return _u
}

// SetNillableUser2HiddenAt sets the "user2_hidden_at" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser2HiddenAt(v *time.Time) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser2HiddenAt(*v)
	}
	return _u
}

// ClearUser2HiddenAt clears the value of the "user2_hidden_at" field.
func (_u *PrivateChatUpdate) ClearUser2HiddenAt() *PrivateChatUpdate {
	_u.mutation.ClearUser2HiddenAt()
	return _u
}

// SetUser1UnreadCount sets the "user1_unread_count" field.
func (_u *PrivateChatUpdate) SetUser1UnreadCount(v int) *PrivateChatUpdate {
	_u.mutation.ResetUser1UnreadCount()
	_u.mutation.SetUser1UnreadCount(v)
	return _u
}

// SetNillableUser1UnreadCount sets the "user1_unread_count" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser1UnreadCount(v *int) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser1UnreadCount(*v)
	}
	return _u
}

// AddUser1UnreadCount adds value to the "user1_unread_count" field.
func (_u *PrivateChatUpdate) AddUser1UnreadCount(v int) *PrivateChatUpdate {
	_u.mutation.AddUser1UnreadCount(v)
	return _u
}

// SetUser2UnreadCount sets the "user2_unread_count" field.
func (_u *PrivateChatUpdate) SetUser2UnreadCount(v int) *PrivateChatUpdate {
	_u.mutation.ResetUser2UnreadCount()
	_u.mutation.SetUser2UnreadCount(v)
	return _u
}

// SetNillableUser2UnreadCount sets the "user2_unread_count" field if the given value is not nil.
func (_u *PrivateChatUpdate) SetNillableUser2UnreadCount(v *int) *PrivateChatUpdate {
	if v != nil {
		_u.SetUser2UnreadCount(*v)
	}
	return _u
}

// AddUser2UnreadCount adds value to the "user2_unread_count" field.
func (_u *PrivateChatUpdate) AddUser2UnreadCount(v int) *PrivateChatUpdate {
	_u.mutation.AddUser2UnreadCount(v)
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *PrivateChatUpdate) SetChat(v *Chat) *PrivateChatUpdate {
	return _u.SetChatID(v.ID)
}

// SetUser1 sets the "user1" edge to the User entity.
func (_u *PrivateChatUpdate) SetUser1(v *User) *PrivateChatUpdate {
	return _u.SetUser1ID(v.ID)
}

// SetUser2 sets the "user2" edge to the User entity.
func (_u *PrivateChatUpdate) SetUser2(v *User) *PrivateChatUpdate {
	return _u.SetUser2ID(v.ID)
}

// Mutation returns the PrivateChatMutation object of the builder.
func (_u *PrivateChatUpdate) Mutation() *PrivateChatMutation {
	return _u.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *PrivateChatUpdate) ClearChat() *PrivateChatUpdate {
	_u.mutation.ClearChat()
	return _u
}

// ClearUser1 clears the "user1" edge to the User entity.
func (_u *PrivateChatUpdate) ClearUser1() *PrivateChatUpdate {
	_u.mutation.ClearUser1()
	return _u
}

// ClearUser2 clears the "user2" edge to the User entity.
func (_u *PrivateChatUpdate) ClearUser2() *PrivateChatUpdate {
	_u.mutation.ClearUser2()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrivateChatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrivateChatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrivateChatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrivateChatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrivateChatUpdate) check() error {
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.chat"`)
	}
	if _u.mutation.User1Cleared() && len(_u.mutation.User1IDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.user1"`)
	}
	if _u.mutation.User2Cleared() && len(_u.mutation.User2IDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.user2"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PrivateChatUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PrivateChatUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PrivateChatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(privatechat.Table, privatechat.Columns, sqlgraph.NewFieldSpec(privatechat.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.User1LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser1LastReadAt, field.TypeTime, value)
	}
	if _u.mutation.User1LastReadAtCleared() {
		_spec.ClearField(privatechat.FieldUser1LastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User2LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser2LastReadAt, field.TypeTime, value)
	}
	if _u.mutation.User2LastReadAtCleared() {
		_spec.ClearField(privatechat.FieldUser2LastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User1HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser1HiddenAt, field.TypeTime, value)
	}
	if _u.mutation.User1HiddenAtCleared() {
		_spec.ClearField(privatechat.FieldUser1HiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User2HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser2HiddenAt, field.TypeTime, value)
	}
	if _u.mutation.User2HiddenAtCleared() {
		_spec.ClearField(privatechat.FieldUser2HiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User1UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser1UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUser1UnreadCount(); ok {
		_spec.AddField(privatechat.FieldUser1UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.User2UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser2UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUser2UnreadCount(); ok {
		_spec.AddField(privatechat.FieldUser2UnreadCount, field.TypeInt, value)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   privatechat.ChatTable,
			Columns: []string{privatechat.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   privatechat.ChatTable,
			Columns: []string{privatechat.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.User1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User1Table,
			Columns: []string{privatechat.User1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.User1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User1Table,
			Columns: []string{privatechat.User1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.User2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User2Table,
			Columns: []string{privatechat.User2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.User2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User2Table,
			Columns: []string{privatechat.User2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatechat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrivateChatUpdateOne is the builder for updating a single PrivateChat entity.
type PrivateChatUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PrivateChatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChatID sets the "chat_id" field.
func (_u *PrivateChatUpdateOne) SetChatID(v uuid.UUID) *PrivateChatUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableChatID(v *uuid.UUID) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetUser1ID sets the "user1_id" field.
func (_u *PrivateChatUpdateOne) SetUser1ID(v uuid.UUID) *PrivateChatUpdateOne {
	_u.mutation.SetUser1ID(v)
	return _u
}

// SetNillableUser1ID sets the "user1_id" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser1ID(v *uuid.UUID) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser1ID(*v)
	}
	return _u
}

// SetUser2ID sets the "user2_id" field.
func (_u *PrivateChatUpdateOne) SetUser2ID(v uuid.UUID) *PrivateChatUpdateOne {
	_u.mutation.SetUser2ID(v)
	return _u
}

// SetNillableUser2ID sets the "user2_id" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser2ID(v *uuid.UUID) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser2ID(*v)
	}
	return _u
}

// SetUser1LastReadAt sets the "user1_last_read_at" field.
func (_u *PrivateChatUpdateOne) SetUser1LastReadAt(v time.Time) *PrivateChatUpdateOne {
	_u.mutation.SetUser1LastReadAt(v)
	return _u
}

// SetNillableUser1LastReadAt sets the "user1_last_read_at" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser1LastReadAt(v *time.Time) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser1LastReadAt(*v)
	}
	return _u
}

// ClearUser1LastReadAt clears the value of the "user1_last_read_at" field.
func (_u *PrivateChatUpdateOne) ClearUser1LastReadAt() *PrivateChatUpdateOne {
	_u.mutation.ClearUser1LastReadAt()
	return _u
}

// SetUser2LastReadAt sets the "user2_last_read_at" field.
func (_u *PrivateChatUpdateOne) SetUser2LastReadAt(v time.Time) *PrivateChatUpdateOne {
	_u.mutation.SetUser2LastReadAt(v)
	return _u
}

// SetNillableUser2LastReadAt sets the "user2_last_read_at" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser2LastReadAt(v *time.Time) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser2LastReadAt(*v)
	}
	return _u
}

// ClearUser2LastReadAt clears the value of the "user2_last_read_at" field.
func (_u *PrivateChatUpdateOne) ClearUser2LastReadAt() *PrivateChatUpdateOne {
	_u.mutation.ClearUser2LastReadAt()
	return _u
}

// SetUser1HiddenAt sets the "user1_hidden_at" field.
func (_u *PrivateChatUpdateOne) SetUser1HiddenAt(v time.Time) *PrivateChatUpdateOne {
	_u.mutation.SetUser1HiddenAt(v)
	return _u
}

// SetNillableUser1HiddenAt sets the "user1_hidden_at" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser1HiddenAt(v *time.Time) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser1HiddenAt(*v)
	}
	return _u
}

// ClearUser1HiddenAt clears the value of the "user1_hidden_at" field.
func (_u *PrivateChatUpdateOne) ClearUser1HiddenAt() *PrivateChatUpdateOne {
	_u.mutation.ClearUser1HiddenAt()
	return _u
}

// SetUser2HiddenAt sets the "user2_hidden_at" field.
func (_u *PrivateChatUpdateOne) SetUser2HiddenAt(v time.Time) *PrivateChatUpdateOne {
	_u.mutation.SetUser2HiddenAt(v)
	return _u
}

// SetNillableUser2HiddenAt sets the "user2_hidden_at" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser2HiddenAt(v *time.Time) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser2HiddenAt(*v)
	}
	return _u
}

// ClearUser2HiddenAt clears the value of the "user2_hidden_at" field.
func (_u *PrivateChatUpdateOne) ClearUser2HiddenAt() *PrivateChatUpdateOne {
	_u.mutation.ClearUser2HiddenAt()
	return _u
}

// SetUser1UnreadCount sets the "user1_unread_count" field.
func (_u *PrivateChatUpdateOne) SetUser1UnreadCount(v int) *PrivateChatUpdateOne {
	_u.mutation.ResetUser1UnreadCount()
	_u.mutation.SetUser1UnreadCount(v)
	return _u
}

// SetNillableUser1UnreadCount sets the "user1_unread_count" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser1UnreadCount(v *int) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser1UnreadCount(*v)
	}
	return _u
}

// AddUser1UnreadCount adds value to the "user1_unread_count" field.
func (_u *PrivateChatUpdateOne) AddUser1UnreadCount(v int) *PrivateChatUpdateOne {
	_u.mutation.AddUser1UnreadCount(v)
	return _u
}

// SetUser2UnreadCount sets the "user2_unread_count" field.
func (_u *PrivateChatUpdateOne) SetUser2UnreadCount(v int) *PrivateChatUpdateOne {
	_u.mutation.ResetUser2UnreadCount()
	_u.mutation.SetUser2UnreadCount(v)
	return _u
}

// SetNillableUser2UnreadCount sets the "user2_unread_count" field if the given value is not nil.
func (_u *PrivateChatUpdateOne) SetNillableUser2UnreadCount(v *int) *PrivateChatUpdateOne {
	if v != nil {
		_u.SetUser2UnreadCount(*v)
	}
	return _u
}

// AddUser2UnreadCount adds value to the "user2_unread_count" field.
func (_u *PrivateChatUpdateOne) AddUser2UnreadCount(v int) *PrivateChatUpdateOne {
	_u.mutation.AddUser2UnreadCount(v)
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *PrivateChatUpdateOne) SetChat(v *Chat) *PrivateChatUpdateOne {
	return _u.SetChatID(v.ID)
}

// SetUser1 sets the "user1" edge to the User entity.
func (_u *PrivateChatUpdateOne) SetUser1(v *User) *PrivateChatUpdateOne {
	return _u.SetUser1ID(v.ID)
}

// SetUser2 sets the "user2" edge to the User entity.
func (_u *PrivateChatUpdateOne) SetUser2(v *User) *PrivateChatUpdateOne {
	return _u.SetUser2ID(v.ID)
}

// Mutation returns the PrivateChatMutation object of the builder.
func (_u *PrivateChatUpdateOne) Mutation() *PrivateChatMutation {
	return _u.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *PrivateChatUpdateOne) ClearChat() *PrivateChatUpdateOne {
	_u.mutation.ClearChat()
	return _u
}

// ClearUser1 clears the "user1" edge to the User entity.
func (_u *PrivateChatUpdateOne) ClearUser1() *PrivateChatUpdateOne {
	_u.mutation.ClearUser1()
	return _u
}

// ClearUser2 clears the "user2" edge to the User entity.
func (_u *PrivateChatUpdateOne) ClearUser2() *PrivateChatUpdateOne {
	_u.mutation.ClearUser2()
	return _u
}

// Where appends a list predicates to the PrivateChatUpdate builder.
func (_u *PrivateChatUpdateOne) Where(ps ...predicate.PrivateChat) *PrivateChatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrivateChatUpdateOne) Select(field string, fields ...string) *PrivateChatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PrivateChat entity.
func (_u *PrivateChatUpdateOne) Save(ctx context.Context) (*PrivateChat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrivateChatUpdateOne) SaveX(ctx context.Context) *PrivateChat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrivateChatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrivateChatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrivateChatUpdateOne) check() error {
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.chat"`)
	}
	if _u.mutation.User1Cleared() && len(_u.mutation.User1IDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.user1"`)
	}
	if _u.mutation.User2Cleared() && len(_u.mutation.User2IDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PrivateChat.user2"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PrivateChatUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PrivateChatUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PrivateChatUpdateOne) sqlSave(ctx context.Context) (_node *PrivateChat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(privatechat.Table, privatechat.Columns, sqlgraph.NewFieldSpec(privatechat.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PrivateChat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, privatechat.FieldID)
		for _, f := range fields {
			if !privatechat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != privatechat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.User1LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser1LastReadAt, field.TypeTime, value)
	}
	if _u.mutation.User1LastReadAtCleared() {
		_spec.ClearField(privatechat.FieldUser1LastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User2LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser2LastReadAt, field.TypeTime, value)
	}
	if _u.mutation.User2LastReadAtCleared() {
		_spec.ClearField(privatechat.FieldUser2LastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User1HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser1HiddenAt, field.TypeTime, value)
	}
	if _u.mutation.User1HiddenAtCleared() {
		_spec.ClearField(privatechat.FieldUser1HiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User2HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser2HiddenAt, field.TypeTime, value)
	}
	if _u.mutation.User2HiddenAtCleared() {
		_spec.ClearField(privatechat.FieldUser2HiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.User1UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser1UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUser1UnreadCount(); ok {
		_spec.AddField(privatechat.FieldUser1UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.User2UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser2UnreadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUser2UnreadCount(); ok {
		_spec.AddField(privatechat.FieldUser2UnreadCount, field.TypeInt, value)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   privatechat.ChatTable,
			Columns: []string{privatechat.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   privatechat.ChatTable,
			Columns: []string{privatechat.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.User1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User1Table,
			Columns: []string{privatechat.User1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.User1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User1Table,
			Columns: []string{privatechat.User1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.User2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User2Table,
			Columns: []string{privatechat.User2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.User2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User2Table,
			Columns: []string{privatechat.User2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PrivateChat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{privatechat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
