// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/chat"
	"AtoiTalkAPI/ent/privatechat"
	"AtoiTalkAPI/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrivateChatCreate is the builder for creating a PrivateChat entity.
type PrivateChatCreate struct {
	config
	mutation *PrivateChatMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (_c *PrivateChatCreate) SetChatID(v int) *PrivateChatCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetUser1ID sets the "user1_id" field.
func (_c *PrivateChatCreate) SetUser1ID(v int) *PrivateChatCreate {
	_c.mutation.SetUser1ID(v)
	return _c
}

// SetUser2ID sets the "user2_id" field.
func (_c *PrivateChatCreate) SetUser2ID(v int) *PrivateChatCreate {
	_c.mutation.SetUser2ID(v)
	return _c
}

// SetUser1LastReadAt sets the "user1_last_read_at" field.
func (_c *PrivateChatCreate) SetUser1LastReadAt(v time.Time) *PrivateChatCreate {
	_c.mutation.SetUser1LastReadAt(v)
	return _c
}

// SetNillableUser1LastReadAt sets the "user1_last_read_at" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser1LastReadAt(v *time.Time) *PrivateChatCreate {
	if v != nil {
		_c.SetUser1LastReadAt(*v)
	}
	return _c
}

// SetUser2LastReadAt sets the "user2_last_read_at" field.
func (_c *PrivateChatCreate) SetUser2LastReadAt(v time.Time) *PrivateChatCreate {
	_c.mutation.SetUser2LastReadAt(v)
	return _c
}

// SetNillableUser2LastReadAt sets the "user2_last_read_at" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser2LastReadAt(v *time.Time) *PrivateChatCreate {
	if v != nil {
		_c.SetUser2LastReadAt(*v)
	}
	return _c
}

// SetUser1HiddenAt sets the "user1_hidden_at" field.
func (_c *PrivateChatCreate) SetUser1HiddenAt(v time.Time) *PrivateChatCreate {
	_c.mutation.SetUser1HiddenAt(v)
	return _c
}

// SetNillableUser1HiddenAt sets the "user1_hidden_at" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser1HiddenAt(v *time.Time) *PrivateChatCreate {
	if v != nil {
		_c.SetUser1HiddenAt(*v)
	}
	return _c
}

// SetUser2HiddenAt sets the "user2_hidden_at" field.
func (_c *PrivateChatCreate) SetUser2HiddenAt(v time.Time) *PrivateChatCreate {
	_c.mutation.SetUser2HiddenAt(v)
	return _c
}

// SetNillableUser2HiddenAt sets the "user2_hidden_at" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser2HiddenAt(v *time.Time) *PrivateChatCreate {
	if v != nil {
		_c.SetUser2HiddenAt(*v)
	}
	return _c
}

// SetUser1UnreadCount sets the "user1_unread_count" field.
func (_c *PrivateChatCreate) SetUser1UnreadCount(v int) *PrivateChatCreate {
	_c.mutation.SetUser1UnreadCount(v)
	return _c
}

// SetNillableUser1UnreadCount sets the "user1_unread_count" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser1UnreadCount(v *int) *PrivateChatCreate {
	if v != nil {
		_c.SetUser1UnreadCount(*v)
	}
	return _c
}

// SetUser2UnreadCount sets the "user2_unread_count" field.
func (_c *PrivateChatCreate) SetUser2UnreadCount(v int) *PrivateChatCreate {
	_c.mutation.SetUser2UnreadCount(v)
	return _c
}

// SetNillableUser2UnreadCount sets the "user2_unread_count" field if the given value is not nil.
func (_c *PrivateChatCreate) SetNillableUser2UnreadCount(v *int) *PrivateChatCreate {
	if v != nil {
		_c.SetUser2UnreadCount(*v)
	}
	return _c
}

// SetChat sets the "chat" edge to the Chat entity.
func (_c *PrivateChatCreate) SetChat(v *Chat) *PrivateChatCreate {
	return _c.SetChatID(v.ID)
}

// SetUser1 sets the "user1" edge to the User entity.
func (_c *PrivateChatCreate) SetUser1(v *User) *PrivateChatCreate {
	return _c.SetUser1ID(v.ID)
}

// SetUser2 sets the "user2" edge to the User entity.
func (_c *PrivateChatCreate) SetUser2(v *User) *PrivateChatCreate {
	return _c.SetUser2ID(v.ID)
}

// Mutation returns the PrivateChatMutation object of the builder.
func (_c *PrivateChatCreate) Mutation() *PrivateChatMutation {
	return _c.mutation
}

// Save creates the PrivateChat in the database.
func (_c *PrivateChatCreate) Save(ctx context.Context) (*PrivateChat, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PrivateChatCreate) SaveX(ctx context.Context) *PrivateChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrivateChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrivateChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PrivateChatCreate) defaults() error {
	if _, ok := _c.mutation.User1UnreadCount(); !ok {
		v := privatechat.DefaultUser1UnreadCount
		_c.mutation.SetUser1UnreadCount(v)
	}
	if _, ok := _c.mutation.User2UnreadCount(); !ok {
		v := privatechat.DefaultUser2UnreadCount
		_c.mutation.SetUser2UnreadCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PrivateChatCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "PrivateChat.chat_id"`)}
	}
	if _, ok := _c.mutation.User1ID(); !ok {
		return &ValidationError{Name: "user1_id", err: errors.New(`ent: missing required field "PrivateChat.user1_id"`)}
	}
	if _, ok := _c.mutation.User2ID(); !ok {
		return &ValidationError{Name: "user2_id", err: errors.New(`ent: missing required field "PrivateChat.user2_id"`)}
	}
	if _, ok := _c.mutation.User1UnreadCount(); !ok {
		return &ValidationError{Name: "user1_unread_count", err: errors.New(`ent: missing required field "PrivateChat.user1_unread_count"`)}
	}
	if _, ok := _c.mutation.User2UnreadCount(); !ok {
		return &ValidationError{Name: "user2_unread_count", err: errors.New(`ent: missing required field "PrivateChat.user2_unread_count"`)}
	}
	if len(_c.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "PrivateChat.chat"`)}
	}
	if len(_c.mutation.User1IDs()) == 0 {
		return &ValidationError{Name: "user1", err: errors.New(`ent: missing required edge "PrivateChat.user1"`)}
	}
	if len(_c.mutation.User2IDs()) == 0 {
		return &ValidationError{Name: "user2", err: errors.New(`ent: missing required edge "PrivateChat.user2"`)}
	}
	return nil
}

func (_c *PrivateChatCreate) sqlSave(ctx context.Context) (*PrivateChat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PrivateChatCreate) createSpec() (*PrivateChat, *sqlgraph.CreateSpec) {
	var (
		_node = &PrivateChat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(privatechat.Table, sqlgraph.NewFieldSpec(privatechat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.User1LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser1LastReadAt, field.TypeTime, value)
		_node.User1LastReadAt = &value
	}
	if value, ok := _c.mutation.User2LastReadAt(); ok {
		_spec.SetField(privatechat.FieldUser2LastReadAt, field.TypeTime, value)
		_node.User2LastReadAt = &value
	}
	if value, ok := _c.mutation.User1HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser1HiddenAt, field.TypeTime, value)
		_node.User1HiddenAt = &value
	}
	if value, ok := _c.mutation.User2HiddenAt(); ok {
		_spec.SetField(privatechat.FieldUser2HiddenAt, field.TypeTime, value)
		_node.User2HiddenAt = &value
	}
	if value, ok := _c.mutation.User1UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser1UnreadCount, field.TypeInt, value)
		_node.User1UnreadCount = value
	}
	if value, ok := _c.mutation.User2UnreadCount(); ok {
		_spec.SetField(privatechat.FieldUser2UnreadCount, field.TypeInt, value)
		_node.User2UnreadCount = value
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   privatechat.ChatTable,
			Columns: []string{privatechat.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChatID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.User1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User1Table,
			Columns: []string{privatechat.User1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.User1ID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.User2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   privatechat.User2Table,
			Columns: []string{privatechat.User2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.User2ID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PrivateChatCreateBulk is the builder for creating many PrivateChat entities in bulk.
type PrivateChatCreateBulk struct {
	config
	err      error
	builders []*PrivateChatCreate
}

// Save creates the PrivateChat entities in the database.
func (_c *PrivateChatCreateBulk) Save(ctx context.Context) ([]*PrivateChat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PrivateChat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrivateChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PrivateChatCreateBulk) SaveX(ctx context.Context) []*PrivateChat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrivateChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrivateChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
