// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/groupchat"
	"AtoiTalkAPI/ent/media"
	"AtoiTalkAPI/ent/message"
	"AtoiTalkAPI/ent/report"
	"AtoiTalkAPI/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTargetType sets the "target_type" field.
func (_c *ReportCreate) SetTargetType(v report.TargetType) *ReportCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *ReportCreate) SetReason(v string) *ReportCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ReportCreate) SetDescription(v string) *ReportCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ReportCreate) SetNillableDescription(v *string) *ReportCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEvidenceSnapshot sets the "evidence_snapshot" field.
func (_c *ReportCreate) SetEvidenceSnapshot(v map[string]interface{}) *ReportCreate {
	_c.mutation.SetEvidenceSnapshot(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReportCreate) SetStatus(v report.Status) *ReportCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReportCreate) SetNillableStatus(v *report.Status) *ReportCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReporterID sets the "reporter_id" field.
func (_c *ReportCreate) SetReporterID(v uuid.UUID) *ReportCreate {
	_c.mutation.SetReporterID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *ReportCreate) SetMessageID(v uuid.UUID) *ReportCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableMessageID(v *uuid.UUID) *ReportCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ReportCreate) SetGroupID(v uuid.UUID) *ReportCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableGroupID(v *uuid.UUID) *ReportCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *ReportCreate) SetTargetUserID(v uuid.UUID) *ReportCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableTargetUserID(v *uuid.UUID) *ReportCreate {
	if v != nil {
		_c.SetTargetUserID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportCreate) SetCreatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableCreatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportCreate) SetUpdatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUpdatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReportCreate) SetID(v uuid.UUID) *ReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableID(v *uuid.UUID) *ReportCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetReporter sets the "reporter" edge to the User entity.
func (_c *ReportCreate) SetReporter(v *User) *ReportCreate {
	return _c.SetReporterID(v.ID)
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *ReportCreate) SetMessage(v *Message) *ReportCreate {
	return _c.SetMessageID(v.ID)
}

// SetGroup sets the "group" edge to the GroupChat entity.
func (_c *ReportCreate) SetGroup(v *GroupChat) *ReportCreate {
	return _c.SetGroupID(v.ID)
}

// SetTargetUser sets the "target_user" edge to the User entity.
func (_c *ReportCreate) SetTargetUser(v *User) *ReportCreate {
	return _c.SetTargetUserID(v.ID)
}

// AddEvidenceMediumIDs adds the "evidence_media" edge to the Media entity by IDs.
func (_c *ReportCreate) AddEvidenceMediumIDs(ids ...uuid.UUID) *ReportCreate {
	_c.mutation.AddEvidenceMediumIDs(ids...)
	return _c
}

// AddEvidenceMedia adds the "evidence_media" edges to the Media entity.
func (_c *ReportCreate) AddEvidenceMedia(v ...*Media) *ReportCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEvidenceMediumIDs(ids...)
}

// Mutation returns the ReportMutation object of the builder.
func (_c *ReportCreate) Mutation() *ReportMutation {
	return _c.mutation
}

// Save creates the Report in the database.
func (_c *ReportCreate) Save(ctx context.Context) (*Report, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := report.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := report.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := report.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := report.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportCreate) check() error {
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "Report.target_type"`)}
	}
	if v, ok := _c.mutation.TargetType(); ok {
		if err := report.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "Report.target_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Report.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReporterID(); !ok {
		return &ValidationError{Name: "reporter_id", err: errors.New(`ent: missing required field "Report.reporter_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Report.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Report.updated_at"`)}
	}
	if len(_c.mutation.ReporterIDs()) == 0 {
		return &ValidationError{Name: "reporter", err: errors.New(`ent: missing required edge "Report.reporter"`)}
	}
	return nil
}

func (_c *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(report.FieldTargetType, field.TypeEnum, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(report.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.EvidenceSnapshot(); ok {
		_spec.SetField(report.FieldEvidenceSnapshot, field.TypeJSON, value)
		_node.EvidenceSnapshot = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReporterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.MessageTable,
			Columns: []string{report.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.GroupTable,
			Columns: []string{report.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupchat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.TargetUserTable,
			Columns: []string{report.TargetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EvidenceMediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   report.EvidenceMediaTable,
			Columns: report.EvidenceMediaPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Report.Create().
//		SetTargetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReportUpsert) {
//			SetTargetType(v+v).
//		}).
//		Exec(ctx)
func (_c *ReportCreate) OnConflict(opts ...sql.ConflictOption) *ReportUpsertOne {
	_c.conflict = opts
	return &ReportUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReportCreate) OnConflictColumns(columns ...string) *ReportUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReportUpsertOne{
		create: _c,
	}
}

type (
	// ReportUpsertOne is the builder for "upsert"-ing
	//  one Report node.
	ReportUpsertOne struct {
		create *ReportCreate
	}

	// ReportUpsert is the "OnConflict" setter.
	ReportUpsert struct {
		*sql.UpdateSet
	}
)

// SetReason sets the "reason" field.
func (u *ReportUpsert) SetReason(v string) *ReportUpsert {
	u.Set(report.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ReportUpsert) UpdateReason() *ReportUpsert {
	u.SetExcluded(report.FieldReason)
	return u
}

// SetDescription sets the "description" field.
func (u *ReportUpsert) SetDescription(v string) *ReportUpsert {
	u.Set(report.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ReportUpsert) UpdateDescription() *ReportUpsert {
	u.SetExcluded(report.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ReportUpsert) ClearDescription() *ReportUpsert {
	u.SetNull(report.FieldDescription)
	return u
}

// SetEvidenceSnapshot sets the "evidence_snapshot" field.
func (u *ReportUpsert) SetEvidenceSnapshot(v map[string]interface{}) *ReportUpsert {
	u.Set(report.FieldEvidenceSnapshot, v)
	return u
}

// UpdateEvidenceSnapshot sets the "evidence_snapshot" field to the value that was provided on create.
func (u *ReportUpsert) UpdateEvidenceSnapshot() *ReportUpsert {
	u.SetExcluded(report.FieldEvidenceSnapshot)
	return u
}

// ClearEvidenceSnapshot clears the value of the "evidence_snapshot" field.
func (u *ReportUpsert) ClearEvidenceSnapshot() *ReportUpsert {
	u.SetNull(report.FieldEvidenceSnapshot)
	return u
}

// SetStatus sets the "status" field.
func (u *ReportUpsert) SetStatus(v report.Status) *ReportUpsert {
	u.Set(report.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsert) UpdateStatus() *ReportUpsert {
	u.SetExcluded(report.FieldStatus)
	return u
}

// SetReporterID sets the "reporter_id" field.
func (u *ReportUpsert) SetReporterID(v uuid.UUID) *ReportUpsert {
	u.Set(report.FieldReporterID, v)
	return u
}

// UpdateReporterID sets the "reporter_id" field to the value that was provided on create.
func (u *ReportUpsert) UpdateReporterID() *ReportUpsert {
	u.SetExcluded(report.FieldReporterID)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *ReportUpsert) SetMessageID(v uuid.UUID) *ReportUpsert {
	u.Set(report.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *ReportUpsert) UpdateMessageID() *ReportUpsert {
	u.SetExcluded(report.FieldMessageID)
	return u
}

// ClearMessageID clears the value of the "message_id" field.
func (u *ReportUpsert) ClearMessageID() *ReportUpsert {
	u.SetNull(report.FieldMessageID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ReportUpsert) SetGroupID(v uuid.UUID) *ReportUpsert {
	u.Set(report.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ReportUpsert) UpdateGroupID() *ReportUpsert {
	u.SetExcluded(report.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ReportUpsert) ClearGroupID() *ReportUpsert {
	u.SetNull(report.FieldGroupID)
	return u
}

// SetTargetUserID sets the "target_user_id" field.
func (u *ReportUpsert) SetTargetUserID(v uuid.UUID) *ReportUpsert {
	u.Set(report.FieldTargetUserID, v)
	return u
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *ReportUpsert) UpdateTargetUserID() *ReportUpsert {
	u.SetExcluded(report.FieldTargetUserID)
	return u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *ReportUpsert) ClearTargetUserID() *ReportUpsert {
	u.SetNull(report.FieldTargetUserID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsert) SetUpdatedAt(v time.Time) *ReportUpsert {
	u.Set(report.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsert) UpdateUpdatedAt() *ReportUpsert {
	u.SetExcluded(report.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(report.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReportUpsertOne) UpdateNewValues() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(report.FieldID)
		}
		if _, exists := u.create.mutation.TargetType(); exists {
			s.SetIgnore(report.FieldTargetType)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(report.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReportUpsertOne) Ignore() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReportUpsertOne) DoNothing() *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReportCreate.OnConflict
// documentation for more info.
func (u *ReportUpsertOne) Update(set func(*ReportUpsert)) *ReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetReason sets the "reason" field.
func (u *ReportUpsertOne) SetReason(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateReason() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateReason()
	})
}

// SetDescription sets the "description" field.
func (u *ReportUpsertOne) SetDescription(v string) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateDescription() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ReportUpsertOne) ClearDescription() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearDescription()
	})
}

// SetEvidenceSnapshot sets the "evidence_snapshot" field.
func (u *ReportUpsertOne) SetEvidenceSnapshot(v map[string]interface{}) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetEvidenceSnapshot(v)
	})
}

// UpdateEvidenceSnapshot sets the "evidence_snapshot" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateEvidenceSnapshot() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateEvidenceSnapshot()
	})
}

// ClearEvidenceSnapshot clears the value of the "evidence_snapshot" field.
func (u *ReportUpsertOne) ClearEvidenceSnapshot() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearEvidenceSnapshot()
	})
}

// SetStatus sets the "status" field.
func (u *ReportUpsertOne) SetStatus(v report.Status) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateStatus() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStatus()
	})
}

// SetReporterID sets the "reporter_id" field.
func (u *ReportUpsertOne) SetReporterID(v uuid.UUID) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetReporterID(v)
	})
}

// UpdateReporterID sets the "reporter_id" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateReporterID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateReporterID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *ReportUpsertOne) SetMessageID(v uuid.UUID) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateMessageID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *ReportUpsertOne) ClearMessageID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearMessageID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ReportUpsertOne) SetGroupID(v uuid.UUID) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateGroupID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ReportUpsertOne) ClearGroupID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearGroupID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *ReportUpsertOne) SetTargetUserID(v uuid.UUID) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateTargetUserID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *ReportUpsertOne) ClearTargetUserID() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.ClearTargetUserID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsertOne) SetUpdatedAt(v time.Time) *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsertOne) UpdateUpdatedAt() *ReportUpsertOne {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReportUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ReportUpsertOne.ID is not supported by MySQL driver. Use ReportUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReportUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
	conflict []sql.ConflictOption
}

// Save creates the Report entities in the database.
func (_c *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Report, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Report.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReportUpsert) {
//			SetTargetType(v+v).
//		}).
//		Exec(ctx)
func (_c *ReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReportUpsertBulk {
	_c.conflict = opts
	return &ReportUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReportCreateBulk) OnConflictColumns(columns ...string) *ReportUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReportUpsertBulk{
		create: _c,
	}
}

// ReportUpsertBulk is the builder for "upsert"-ing
// a bulk of Report nodes.
type ReportUpsertBulk struct {
	create *ReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(report.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReportUpsertBulk) UpdateNewValues() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(report.FieldID)
			}
			if _, exists := b.mutation.TargetType(); exists {
				s.SetIgnore(report.FieldTargetType)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(report.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Report.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReportUpsertBulk) Ignore() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReportUpsertBulk) DoNothing() *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReportCreateBulk.OnConflict
// documentation for more info.
func (u *ReportUpsertBulk) Update(set func(*ReportUpsert)) *ReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetReason sets the "reason" field.
func (u *ReportUpsertBulk) SetReason(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateReason() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateReason()
	})
}

// SetDescription sets the "description" field.
func (u *ReportUpsertBulk) SetDescription(v string) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateDescription() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ReportUpsertBulk) ClearDescription() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearDescription()
	})
}

// SetEvidenceSnapshot sets the "evidence_snapshot" field.
func (u *ReportUpsertBulk) SetEvidenceSnapshot(v map[string]interface{}) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetEvidenceSnapshot(v)
	})
}

// UpdateEvidenceSnapshot sets the "evidence_snapshot" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateEvidenceSnapshot() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateEvidenceSnapshot()
	})
}

// ClearEvidenceSnapshot clears the value of the "evidence_snapshot" field.
func (u *ReportUpsertBulk) ClearEvidenceSnapshot() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearEvidenceSnapshot()
	})
}

// SetStatus sets the "status" field.
func (u *ReportUpsertBulk) SetStatus(v report.Status) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateStatus() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateStatus()
	})
}

// SetReporterID sets the "reporter_id" field.
func (u *ReportUpsertBulk) SetReporterID(v uuid.UUID) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetReporterID(v)
	})
}

// UpdateReporterID sets the "reporter_id" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateReporterID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateReporterID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *ReportUpsertBulk) SetMessageID(v uuid.UUID) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateMessageID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *ReportUpsertBulk) ClearMessageID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearMessageID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ReportUpsertBulk) SetGroupID(v uuid.UUID) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateGroupID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ReportUpsertBulk) ClearGroupID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearGroupID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *ReportUpsertBulk) SetTargetUserID(v uuid.UUID) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateTargetUserID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *ReportUpsertBulk) ClearTargetUserID() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.ClearTargetUserID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReportUpsertBulk) SetUpdatedAt(v time.Time) *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReportUpsertBulk) UpdateUpdatedAt() *ReportUpsertBulk {
	return u.Update(func(s *ReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
