// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/tempcodes"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TempCodesCreate is the builder for creating a TempCodes entity.
type TempCodesCreate struct {
	config
	mutation *TempCodesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TempCodesCreate) SetCreatedAt(v time.Time) *TempCodesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TempCodesCreate) SetNillableCreatedAt(v *time.Time) *TempCodesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TempCodesCreate) SetUpdatedAt(v time.Time) *TempCodesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TempCodesCreate) SetNillableUpdatedAt(v *time.Time) *TempCodesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *TempCodesCreate) SetEmail(v string) *TempCodesCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *TempCodesCreate) SetCode(v string) *TempCodesCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *TempCodesCreate) SetMode(v tempcodes.Mode) *TempCodesCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *TempCodesCreate) SetNillableMode(v *tempcodes.Mode) *TempCodesCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TempCodesCreate) SetExpiresAt(v time.Time) *TempCodesCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the TempCodesMutation object of the builder.
func (_c *TempCodesCreate) Mutation() *TempCodesMutation {
	return _c.mutation
}

// Save creates the TempCodes in the database.
func (_c *TempCodesCreate) Save(ctx context.Context) (*TempCodes, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TempCodesCreate) SaveX(ctx context.Context) *TempCodes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempCodesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempCodesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TempCodesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tempcodes.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tempcodes.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := tempcodes.DefaultMode
		_c.mutation.SetMode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TempCodesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TempCodes.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TempCodes.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "TempCodes.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := tempcodes.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TempCodes.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "TempCodes.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := tempcodes.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TempCodes.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "TempCodes.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := tempcodes.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "TempCodes.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TempCodes.expires_at"`)}
	}
	return nil
}

func (_c *TempCodesCreate) sqlSave(ctx context.Context) (*TempCodes, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TempCodesCreate) createSpec() (*TempCodes, *sqlgraph.CreateSpec) {
	var (
		_node = &TempCodes{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tempcodes.Table, sqlgraph.NewFieldSpec(tempcodes.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tempcodes.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tempcodes.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(tempcodes.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(tempcodes.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(tempcodes.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(tempcodes.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// TempCodesCreateBulk is the builder for creating many TempCodes entities in bulk.
type TempCodesCreateBulk struct {
	config
	err      error
	builders []*TempCodesCreate
}

// Save creates the TempCodes entities in the database.
func (_c *TempCodesCreateBulk) Save(ctx context.Context) ([]*TempCodes, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TempCodes, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TempCodesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TempCodesCreateBulk) SaveX(ctx context.Context) []*TempCodes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempCodesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempCodesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
