// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/predicate"
	"AtoiTalkAPI/ent/tempcodes"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TempCodesUpdate is the builder for updating TempCodes entities.
type TempCodesUpdate struct {
	config
	hooks    []Hook
	mutation *TempCodesMutation
}

// Where appends a list predicates to the TempCodesUpdate builder.
func (_u *TempCodesUpdate) Where(ps ...predicate.TempCodes) *TempCodesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TempCodesUpdate) SetUpdatedAt(v time.Time) *TempCodesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *TempCodesUpdate) SetEmail(v string) *TempCodesUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TempCodesUpdate) SetNillableEmail(v *string) *TempCodesUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TempCodesUpdate) SetCode(v string) *TempCodesUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TempCodesUpdate) SetNillableCode(v *string) *TempCodesUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *TempCodesUpdate) SetMode(v tempcodes.Mode) *TempCodesUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *TempCodesUpdate) SetNillableMode(v *tempcodes.Mode) *TempCodesUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// Mutation returns the TempCodesMutation object of the builder.
func (_u *TempCodesUpdate) Mutation() *TempCodesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TempCodesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TempCodesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TempCodesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TempCodesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TempCodesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tempcodes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TempCodesUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := tempcodes.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TempCodes.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tempcodes.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TempCodes.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := tempcodes.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "TempCodes.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *TempCodesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tempcodes.Table, tempcodes.Columns, sqlgraph.NewFieldSpec(tempcodes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tempcodes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(tempcodes.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tempcodes.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(tempcodes.FieldMode, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tempcodes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TempCodesUpdateOne is the builder for updating a single TempCodes entity.
type TempCodesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TempCodesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TempCodesUpdateOne) SetUpdatedAt(v time.Time) *TempCodesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *TempCodesUpdateOne) SetEmail(v string) *TempCodesUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TempCodesUpdateOne) SetNillableEmail(v *string) *TempCodesUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TempCodesUpdateOne) SetCode(v string) *TempCodesUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TempCodesUpdateOne) SetNillableCode(v *string) *TempCodesUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *TempCodesUpdateOne) SetMode(v tempcodes.Mode) *TempCodesUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *TempCodesUpdateOne) SetNillableMode(v *tempcodes.Mode) *TempCodesUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// Mutation returns the TempCodesMutation object of the builder.
func (_u *TempCodesUpdateOne) Mutation() *TempCodesMutation {
	return _u.mutation
}

// Where appends a list predicates to the TempCodesUpdate builder.
func (_u *TempCodesUpdateOne) Where(ps ...predicate.TempCodes) *TempCodesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TempCodesUpdateOne) Select(field string, fields ...string) *TempCodesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TempCodes entity.
func (_u *TempCodesUpdateOne) Save(ctx context.Context) (*TempCodes, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TempCodesUpdateOne) SaveX(ctx context.Context) *TempCodes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TempCodesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TempCodesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TempCodesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tempcodes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TempCodesUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := tempcodes.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TempCodes.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tempcodes.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TempCodes.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := tempcodes.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "TempCodes.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *TempCodesUpdateOne) sqlSave(ctx context.Context) (_node *TempCodes, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tempcodes.Table, tempcodes.Columns, sqlgraph.NewFieldSpec(tempcodes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TempCodes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tempcodes.FieldID)
		for _, f := range fields {
			if !tempcodes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tempcodes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tempcodes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(tempcodes.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tempcodes.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(tempcodes.FieldMode, field.TypeEnum, value)
	}
	_node = &TempCodes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tempcodes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
