// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/user"
	"AtoiTalkAPI/ent/userblock"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserBlockCreate is the builder for creating a UserBlock entity.
type UserBlockCreate struct {
	config
	mutation *UserBlockMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserBlockCreate) SetCreatedAt(v time.Time) *UserBlockCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserBlockCreate) SetNillableCreatedAt(v *time.Time) *UserBlockCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserBlockCreate) SetUpdatedAt(v time.Time) *UserBlockCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserBlockCreate) SetNillableUpdatedAt(v *time.Time) *UserBlockCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBlockerID sets the "blocker_id" field.
func (_c *UserBlockCreate) SetBlockerID(v int) *UserBlockCreate {
	_c.mutation.SetBlockerID(v)
	return _c
}

// SetBlockedID sets the "blocked_id" field.
func (_c *UserBlockCreate) SetBlockedID(v int) *UserBlockCreate {
	_c.mutation.SetBlockedID(v)
	return _c
}

// SetBlocker sets the "blocker" edge to the User entity.
func (_c *UserBlockCreate) SetBlocker(v *User) *UserBlockCreate {
	return _c.SetBlockerID(v.ID)
}

// SetBlocked sets the "blocked" edge to the User entity.
func (_c *UserBlockCreate) SetBlocked(v *User) *UserBlockCreate {
	return _c.SetBlockedID(v.ID)
}

// Mutation returns the UserBlockMutation object of the builder.
func (_c *UserBlockCreate) Mutation() *UserBlockMutation {
	return _c.mutation
}

// Save creates the UserBlock in the database.
func (_c *UserBlockCreate) Save(ctx context.Context) (*UserBlock, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserBlockCreate) SaveX(ctx context.Context) *UserBlock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBlockCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBlockCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserBlockCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userblock.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userblock.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserBlockCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserBlock.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserBlock.updated_at"`)}
	}
	if _, ok := _c.mutation.BlockerID(); !ok {
		return &ValidationError{Name: "blocker_id", err: errors.New(`ent: missing required field "UserBlock.blocker_id"`)}
	}
	if _, ok := _c.mutation.BlockedID(); !ok {
		return &ValidationError{Name: "blocked_id", err: errors.New(`ent: missing required field "UserBlock.blocked_id"`)}
	}
	if len(_c.mutation.BlockerIDs()) == 0 {
		return &ValidationError{Name: "blocker", err: errors.New(`ent: missing required edge "UserBlock.blocker"`)}
	}
	if len(_c.mutation.BlockedIDs()) == 0 {
		return &ValidationError{Name: "blocked", err: errors.New(`ent: missing required edge "UserBlock.blocked"`)}
	}
	return nil
}

func (_c *UserBlockCreate) sqlSave(ctx context.Context) (*UserBlock, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserBlockCreate) createSpec() (*UserBlock, *sqlgraph.CreateSpec) {
	var (
		_node = &UserBlock{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userblock.Table, sqlgraph.NewFieldSpec(userblock.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userblock.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userblock.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.BlockerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userblock.BlockerTable,
			Columns: []string{userblock.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlockerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userblock.BlockedTable,
			Columns: []string{userblock.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlockedID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserBlockCreateBulk is the builder for creating many UserBlock entities in bulk.
type UserBlockCreateBulk struct {
	config
	err      error
	builders []*UserBlockCreate
}

// Save creates the UserBlock entities in the database.
func (_c *UserBlockCreateBulk) Save(ctx context.Context) ([]*UserBlock, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserBlock, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserBlockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserBlockCreateBulk) SaveX(ctx context.Context) []*UserBlock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBlockCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBlockCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
