// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/user"
	"AtoiTalkAPI/ent/userblock"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UserBlock is the model entity for the UserBlock schema.
type UserBlock struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BlockerID holds the value of the "blocker_id" field.
	BlockerID uuid.UUID `json:"blocker_id,omitempty"`
	// BlockedID holds the value of the "blocked_id" field.
	BlockedID uuid.UUID `json:"blocked_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserBlockQuery when eager-loading is set.
	Edges        UserBlockEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserBlockEdges holds the relations/edges for other nodes in the graph.
type UserBlockEdges struct {
	// Blocker holds the value of the blocker edge.
	Blocker *User `json:"blocker,omitempty"`
	// Blocked holds the value of the blocked edge.
	Blocked *User `json:"blocked,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BlockerOrErr returns the Blocker value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBlockEdges) BlockerOrErr() (*User, error) {
	if e.Blocker != nil {
		return e.Blocker, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "blocker"}
}

// BlockedOrErr returns the Blocked value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBlockEdges) BlockedOrErr() (*User, error) {
	if e.Blocked != nil {
		return e.Blocked, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "blocked"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBlock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userblock.FieldCreatedAt, userblock.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case userblock.FieldID, userblock.FieldBlockerID, userblock.FieldBlockedID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBlock fields.
func (_m *UserBlock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userblock.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case userblock.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userblock.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userblock.FieldBlockerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field blocker_id", values[i])
			} else if value != nil {
				_m.BlockerID = *value
			}
		case userblock.FieldBlockedID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field blocked_id", values[i])
			} else if value != nil {
				_m.BlockedID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBlock.
// This includes values selected through modifiers, order, etc.
func (_m *UserBlock) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBlocker queries the "blocker" edge of the UserBlock entity.
func (_m *UserBlock) QueryBlocker() *UserQuery {
	return NewUserBlockClient(_m.config).QueryBlocker(_m)
}

// QueryBlocked queries the "blocked" edge of the UserBlock entity.
func (_m *UserBlock) QueryBlocked() *UserQuery {
	return NewUserBlockClient(_m.config).QueryBlocked(_m)
}

// Update returns a builder for updating this UserBlock.
// Note that you need to call UserBlock.Unwrap() before calling this method if this UserBlock
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserBlock) Update() *UserBlockUpdateOne {
	return NewUserBlockClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserBlock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserBlock) Unwrap() *UserBlock {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBlock is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserBlock) String() string {
	var builder strings.Builder
	builder.WriteString("UserBlock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("blocker_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockerID))
	builder.WriteString(", ")
	builder.WriteString("blocked_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockedID))
	builder.WriteByte(')')
	return builder.String()
}

// UserBlocks is a parsable slice of UserBlock.
type UserBlocks []*UserBlock
