// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/user"
	"AtoiTalkAPI/ent/useridentity"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserIdentityCreate is the builder for creating a UserIdentity entity.
type UserIdentityCreate struct {
	config
	mutation *UserIdentityMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserIdentityCreate) SetCreatedAt(v time.Time) *UserIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableCreatedAt(v *time.Time) *UserIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserIdentityCreate) SetUpdatedAt(v time.Time) *UserIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableUpdatedAt(v *time.Time) *UserIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserIdentityCreate) SetUserID(v int) *UserIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UserIdentityCreate) SetProvider(v useridentity.Provider) *UserIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableProvider(v *useridentity.Provider) *UserIdentityCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *UserIdentityCreate) SetProviderID(v string) *UserIdentityCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetProviderEmail sets the "provider_email" field.
func (_c *UserIdentityCreate) SetProviderEmail(v string) *UserIdentityCreate {
	_c.mutation.SetProviderEmail(v)
	return _c
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableProviderEmail(v *string) *UserIdentityCreate {
	if v != nil {
		_c.SetProviderEmail(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserIdentityCreate) SetUser(v *User) *UserIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_c *UserIdentityCreate) Mutation() *UserIdentityMutation {
	return _c.mutation
}

// Save creates the UserIdentity in the database.
func (_c *UserIdentityCreate) Save(ctx context.Context) (*UserIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserIdentityCreate) SaveX(ctx context.Context) *UserIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useridentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useridentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := useridentity.DefaultProvider
		_c.mutation.SetProvider(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserIdentityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserIdentity.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserIdentity.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "UserIdentity.provider_id"`)}
	}
	if v, ok := _c.mutation.ProviderID(); ok {
		if err := useridentity.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderEmail(); ok {
		if err := useridentity.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_email": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserIdentity.user"`)}
	}
	return nil
}

func (_c *UserIdentityCreate) sqlSave(ctx context.Context) (*UserIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserIdentityCreate) createSpec() (*UserIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useridentity.Table, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useridentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(useridentity.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.ProviderEmail(); ok {
		_spec.SetField(useridentity.FieldProviderEmail, field.TypeString, value)
		_node.ProviderEmail = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserIdentityCreateBulk is the builder for creating many UserIdentity entities in bulk.
type UserIdentityCreateBulk struct {
	config
	err      error
	builders []*UserIdentityCreate
}

// Save creates the UserIdentity entities in the database.
func (_c *UserIdentityCreateBulk) Save(ctx context.Context) ([]*UserIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserIdentityCreateBulk) SaveX(ctx context.Context) []*UserIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
