// Code generated by ent, DO NOT EDIT.

package userblock

import (
	"AtoiTalkAPI/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldUpdatedAt, v))
}

// BlockerID applies equality check predicate on the "blocker_id" field. It's identical to BlockerIDEQ.
func BlockerID(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldBlockerID, v))
}

// BlockedID applies equality check predicate on the "blocked_id" field. It's identical to BlockedIDEQ.
func BlockedID(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldBlockedID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldLTE(FieldUpdatedAt, v))
}

// BlockerIDEQ applies the EQ predicate on the "blocker_id" field.
func BlockerIDEQ(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldBlockerID, v))
}

// BlockerIDNEQ applies the NEQ predicate on the "blocker_id" field.
func BlockerIDNEQ(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNEQ(FieldBlockerID, v))
}

// BlockerIDIn applies the In predicate on the "blocker_id" field.
func BlockerIDIn(vs ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldIn(FieldBlockerID, vs...))
}

// BlockerIDNotIn applies the NotIn predicate on the "blocker_id" field.
func BlockerIDNotIn(vs ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNotIn(FieldBlockerID, vs...))
}

// BlockedIDEQ applies the EQ predicate on the "blocked_id" field.
func BlockedIDEQ(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldEQ(FieldBlockedID, v))
}

// BlockedIDNEQ applies the NEQ predicate on the "blocked_id" field.
func BlockedIDNEQ(v uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNEQ(FieldBlockedID, v))
}

// BlockedIDIn applies the In predicate on the "blocked_id" field.
func BlockedIDIn(vs ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldIn(FieldBlockedID, vs...))
}

// BlockedIDNotIn applies the NotIn predicate on the "blocked_id" field.
func BlockedIDNotIn(vs ...uuid.UUID) predicate.UserBlock {
	return predicate.UserBlock(sql.FieldNotIn(FieldBlockedID, vs...))
}

// HasBlocker applies the HasEdge predicate on the "blocker" edge.
func HasBlocker() predicate.UserBlock {
	return predicate.UserBlock(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlockerTable, BlockerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlockerWith applies the HasEdge predicate on the "blocker" edge with a given conditions (other predicates).
func HasBlockerWith(preds ...predicate.User) predicate.UserBlock {
	return predicate.UserBlock(func(s *sql.Selector) {
		step := newBlockerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlocked applies the HasEdge predicate on the "blocked" edge.
func HasBlocked() predicate.UserBlock {
	return predicate.UserBlock(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlockedTable, BlockedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlockedWith applies the HasEdge predicate on the "blocked" edge with a given conditions (other predicates).
func HasBlockedWith(preds ...predicate.User) predicate.UserBlock {
	return predicate.UserBlock(func(s *sql.Selector) {
		step := newBlockedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserBlock) predicate.UserBlock {
	return predicate.UserBlock(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserBlock) predicate.UserBlock {
	return predicate.UserBlock(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserBlock) predicate.UserBlock {
	return predicate.UserBlock(sql.NotPredicates(p))
}
